### ISSUE TITLE
[São Paulo/SP | Remoto] Vue.js Developer @ Port Louis

### ISSUE THREAD

**Issue by eduardonoronha** [vuejs-br/vagas#105]
Somos uma empresa de tecnologia que desenvolve produtos de RPA com impacto direto nos resultados dos nossos clientes. Possuímos uma sólida base de projetos já em operação e uma carteira importante de backlog.

O nosso front está desenvolvido em vue, acessando uma plataforma de APIs desenvolvida em microsserviços com node.js.

Procuramos desenvolvedores para implementar novas funcionalidades e fornecer manutenção ao código atual.

Possuímos flexibilidade para trabalho local ou remoto, e forma de contratação CLT ou PJ.

Caso possua interesse, envie e-mail para eduardo@portlouis.inf.br

**Comment by DanielLCintra** [comment]
Aceita em formato de freela ou só contratação full?

**Comment by eduardonoronha** [comment]
> Aceita em formato de freela ou só contratação full?

Pode ser freela, dedicacao minima de 20 horas semanais.

**Comment by ErickPetru** [comment]
Olá @eduardonoronha, por favor, informo o nível do profissional desejado (júnior, pleno, sênior) para podermos classificar corretamente a vaga.

**Comment by eduardonoronha** [comment]
@ErickPetru Obrigado pela resposta. A posição pode ser pleno ou sênior.

**Comment by DanielLCintra** [comment]
@eduardonoronha Enviei email com o meu CV, se quiser podemos conversar para eu entender melhor o projeto.

**Comment by eduardonoronha** [comment]
Desculpa, pessoal, estive fora no final do ano. Eu respondo todo mundo ao longo da semana.

**Comment by eduardonoronha** [comment]
Pessoal, a vaga já foi preenchida, mas temos perspectiva de nova abertura em breve. Se quiserem podem continuar mandando o curriculo, que vai entrar no banco para as próximas vagas.
