### ISSUE TITLE
[Lisboa/PT] Vue.js Developer (+ 2 anos) @ Aubay Portugal

### ISSUE THREAD

**Issue by festaca** [vuejs-br/vagas#11]
### **A nossa empresa**
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 6000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

### **Benefícios**
Plano de saúde
Visto de Trabalho para Portugal
Bilhete de avião para Portugal
Pagamento do alojamento nas primeiras semanas
Cultura organizacional gerida pelo nosso Hapiness Manager
Horário flexível
Almoço grátis todas as sexta-feiras
Frigobar e café grátis
Eventos mensais com atividades diferenciadas
Apoio financeiro

### **Descrição da vaga**
Projetos diferenciados em vários setores de atividade utilizando tecnologias de desenvolvimento frontend em projetos Web e/ou Mobile para projetos nacionais e internacionais

### **Requisitos Obrigatórios**
2 anos de experiência em desenvolvimento Front-end com Vue.js
Conhecimentos em programação orientada a objetos (em uma ou algumas dessas tecnologias): Java, .NET, Javascript, React.js, Node.js, Angular
Nível de inglês avançado

### **Diferenciais**
Projetos internacionais web ou mobile que permitem contato com vários países
Experiência biliotecas e frameworks diferenciadas de javascript

### **Como se candidatar**
Por favor envie um email para [fpiedade@aubay.com](mailto:fpiedade@aubay.com) com seu CV anexado

**Comment by danielschmitz** [comment]
" Java, .NET, Javascript, React.js, Node.js, Angular "
é brincadeira né? Empresa com esse perfil que nem sabe o que quer.. fujam

**Comment by festaca** [comment]
@danielschmitz , 
Obrigado pelo teu comentário pertinente. O objetivo não é encontrar alguém que tenha experiência em todas essas tecnologias, mas sim em algumas delas e vontade de aprender outras novas. Na Aubay gostamos muito de brincar e conviver mas fora do local de trabalho. Somos muito profissionais e temos as melhores pessoas a trabalhar connosco. Se com "fujam" queres dizer para fugir para a Aubay então força, tenho todo o gosto eu conhecer novas pessoas e ajudar a encontrar novos desafios profissionais :)
Boa sorte para ti e para todos os desafios profissionais que surjam na tua vida!

**Comment by danielschmitz** [comment]
Então não coloque como requisito obrigatório 🙃

Veja a vaga da Frente Corretora por exemplo

**Comment by IgorHalfeld** [comment]
@festaca Opa! tomei a liberdade de colocar o trecho 

> em uma ou algumas dessas tecnologias

para a galera não pensar que são todas as tecnologias e ter algum mal entendido de novo :)
confere por favor se é o que você quis dizer

**Comment by festaca** [comment]
@IgorHalfeld opa muito obrigado! está muito bom assim!
