### ISSUE TITLE
[Belo Horizonte/MG | BH/MG | Front-end Vue.js Developer @Ecobonuz

### ISSUE THREAD

**Issue by rafaelmagal** [vuejs-br/vagas#121]
## Descrição da vaga

Procura-se um(a) nerd!
Queremos alguém que goste de tecnologia e que queira desenvolver uma plataforma fantástica, utilizando diversas tecnologias, compartilhando ideias e ajudando a equipe a ser cada vez melhor.

Trabalhamos com metodologias ágeis e queremos alguém assim! Proativo(a) e que queria fazer parte desse time sensacional.

## Local

Escritório em Belo Horizonte/MG.

## Benefícios

Vale Alimentação ou Refeição - R$25/dia;
Vale Transporte;
Plano de Saúde - Bradesco;
Plano Odontológico - Bradesco;
Gympass;
Seguro de Vida;
Day Off mensal - uma folga por mês!
Lanches e frutas no escritório;
No Dress Code - Seja você!
Horário flexível.

## Requisitos

Conhecimento Avançado
JavaScript;
API REST;
HTML 5 + CSS3;
ES6 e ES7;
Protocolo HTTP;
VueJS;
Sass,

Conhecimento Intermediário
Cordova;

Conhecimento Desejável
Conhecimentos em frameworks atuais, como Angular, Ember, React;
LESS.

**Diferenciais:**
- Conhecimentos em Vuex
- Conhecimentos em GraphQL

## Contratação

CLT

## Como se candidatar

Interessad@s podem se candidatar através do link: http://bit.ly/frontecobonuz

#### Alocação
- Presencial

#### Experiência
- Sênior

#### Regime
- CLT

**Comment by DanielLCintra** [comment]
Opa, gostaria de mandar, mas o e-mail acho que está errado "email@empresa.com.br"

**Comment by rafaelmagal** [comment]
> Opa, gostaria de mandar, mas o e-mail acho que está errado "[email@empresa.com.br](mailto:email@empresa.com.br)"

Olá, atualizado!
Você pode se cadastrar no link: http://bit.ly/frontecobonuz

**Comment by fcpmagalhaes** [comment]
A vaga aceita trabalho remoto como indicado nas labels? Ou somente presencial?
