### ISSUE TITLE
[Florianópolis/SC | Remoto] Front-end SR @ Reviewr

### ISSUE THREAD

**Issue by leonardorifeli** [vuejs-br/vagas#131]
# Sobre a Reviewr

Cada vez mais pessoas estão utilizando as avaliações online (reviews) para decidir os serviços e produtos que vão adquirir. Com a Reviewr as empresas passam a controlar e utilizar essa inteligência à favor do próprio negócio, potencializando os resultados, melhorando a reputação online de forma rápida e eficiente, abrindo vantagem sobre os concorrentes e transformando os seus clientes em embaixadores da sua marca.

Somos uma empresa de base tecnológica, mais conhecida como uma “startup”. Nossa plataforma oferece a consolidação de todas as plataformas de Reviews e através dela somos capazes de aumentar o rendimento de qualquer negócio.

Temos apenas dois anos de operação e neste pouco tempo já conquistamos milestones importantíssimos! Já possuímos grandes clientes, ARR relevante, já recebemos rodada de investimentos da Darwin Startups (eleita melhor aceleradora do Brasil), estamos incubados no MIDITEC (5ª melhor incubadora do mundo) e seguimos como uma das startups mais quentes para se trabalhar em Florianópolis. Nossa sede fica no Rio Tavares, um dos bairros mais descolados de Floripa, numa casa super astral, perto de vários restaurantes bacanas e comércio local, onde alinhamos trabalho com qualidade de vida.

# Atividade da vaga

- Desenvolvimento e manutenção de uma aplicação front-end;
- Desenvolvimento de novas features;
- Componentização de interfaces VueJS;
- Estruturação de arquitetura front-end visando desenvolvimento de novos produtos VueJS;
- Manter nosso legado construído em Angular 1.6;
- Manter componentes feitos em Vue.js;
- Contrução de uma nova aplicação front-end, utilizando mais novas tecnologias para componentização.

# Requisitos

- Desenvolver códigos: estáveis, confiáveis, elegantes e, não menos importante, fáceis de manter;
- Desenvolver soluções sempre pensando em eficiência, escalabilidade, disponibilidade, performance e estabilidade. Queremos garantir nosso crescimento super acelerado e um software escalável de maneira econômica (do more with less);
- Desenvolver testes automatizados e CR (code reviews) para garantia de qualidade;
- Conhecimento profundo em Javascript;
- Conhecimento profundo em Vue.js
- Conhecimento em Angular 1.6;
- Conhecimento em webcomponents;
- Experiência e conhecimento em arquitetura front-end;
- Conhecimento em CSS e pré-processadores como LESS, Sass ou PostCSS;
- Conhecimento em arquitetura front-end, usabilidade, performance e testabilidade;
- Experiência na resolução de bugs;
- Conhecimento em conceitos como Clean Code, Clean Architecture, 12 factors app, Design - Patterns e SOLID;
- Vivência com pelo menos um banco de dados relacional;
- Conhecimento e vivência com arquitetura de software;
- Ter comunicação rápida e assertiva, saber trabalhar com times multidisciplinares e enxutos em um ambiente dinâmico, com entregas rápidas, metodologias ágeis e inspirado no Vale do Silício. Trabalhamos com velocidade e autonomia no dia-a-dia e somos um time de alta performance.

# Informações Gerais

- Local: Florianópolis - SC;
- Benefícios: Salário até 5.5k + bônus;
- Contratação / Regime: PJ;
- Alocação: Remoto;
- Mais informações / Candidatar-se: bit.ly/reviewr-senior-frontend-developer.

P.S.: Mais dúvidas, contactar leonardo.rifeli@reviewr.me

**Comment by ErickPetru** [comment]
Olá @leonardorifeli, tudo bem? Por favor, não estabeleça a vaga como remota por causa da pandemia, uma vez que teletrabalho neste período não é um diferencial, é simplesmente o padrão mundial. O importante para os interessados é saber o regime de alocação normal.

**Comment by leonardorifeli** [comment]
@ErickPetru obrigado.
Ajustei para remoto pois é a prioridade para este ano.

**Comment by leonardorifeli** [comment]
A vaga continua aberta e coletando perfis.

**Comment by borgestj** [comment]
Fala Leonardo. Tudo bom?
Dei uma olhada na vaga, vocês possuem vaga para front vue júnior?
Abraços.
