### ISSUE TITLE
[Goiânia/GO | Remoto] Pleno/Senior Front-end Vue.js Developer @ Provendor

### ISSUE THREAD

**Issue by arimourao** [vuejs-br/vagas#132]
## Descrição da vaga

Projeto em andamento necessita de profissionais de nível pleno/sênior em VueJS para manter/desenvolver novas funcionalidades em um frontend desenvolvido com NuxtJS com bootstrap 4. Temos demanda tanto para profissionais freelancers ou full-time.

## Local

Remoto ou Escritório, Goiânia/GO

## Requisitos

**Obrigatórios:**
- 3 + anos de experiência com desenvolvimento JavaScript
- 2 + anos de experiência com desenvolvimento Vue.js
- Conhecimentos com testes unitários
- Conhecimentos em Vuex
- Boa fluência em Javascript ES6

**Desejáveis:**
- Experiência com NuxtJS

## Contratação

PJ a combinar.

## Nossa empresa

Nossa empresa propõe-se a lançar uma plataforma inovadora para ajudar anunciantes do comércio online.

**Aqui usamos:**
- Vue.js
- Node
- RabbitMQ
- Redis
- Golang
- Entre outras tecnologias

## Como se candidatar

Por favor, envie um e-mail para amlima@gmail.com com seu CV anexado. Enviar no assunto: _Vaga Vue.js_

#### Alocação
- Flexível
- Presencial
- Remoto

#### Experiência
- Pleno
- Sênior

#### Regime
- Freela
- PJ

**Comment by LucasLeandroBR** [comment]
Passo

**Comment by ErickPetru** [comment]
@LucasLeandroBR, a menos que tenha comentários relevantes a serem compartilhados com outros membros da comunidade sobre esta empresa ou este recrutador, não convém realizar este tipo de comentário.

**Comment by LucasLeandroBR** [comment]
@ErickPetru Não entendi, você está me advertindo por não fazer nada ?
Não falei nada sobre ninguém

**Comment by ErickPetru** [comment]
@LucasLeandroBR estou lhe advertindo por este comentário "Passo" sem maiores esclarecimentos. Se você já conhece a empresa e deseja compartilhar com os outros alguma experiência passada, sinta-se à vontade. Se apenas não está interessado por qualquer outro motivo pessoal que não deseja declarar, simplesmente não comente. Não é relevante para a comunidade.

**Comment by LucasLeandroBR** [comment]
Tudo bem foi removido, agora você pode remover o teus comentários sobre mim, já que entramos em acordo ?
