### ISSUE TITLE
[Remoto] Full Stak Developer (Vue.js + Node.js)

### ISSUE THREAD

**Issue by alexandremaeda** [vuejs-br/vagas#15]
## Descrição da vaga

Ferramenta para facilitar o mercado de Energia Solar Fotovoltaica.

## Local

Remoto ou Escritório, Ribeirão Preto - SP

## Requisitos

**Obrigatórios:**
- Javascript
- Node.js
- Vue.js

**Desejáveis:**
- Express.js
- Sequelize.js
- MySQL
- Git

## Contratação

Freela

## Nossa empresa

Agência de MKT Digital

## Como se candidatar

Por favor envie um email para ale.b.maeda@gmail.com com seu CV anexado - enviar no assunto: Vaga Vue.js + Node.js

## Labels

- alocação/Flexível
- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/Freela

**Comment by rogeriomq** [comment]
Quem vaga linda! Quem me dera...
