### ISSUE TITLE
[Curitiba/PR] - Tech Lead @ Contabilizei

### ISSUE THREAD

**Issue by carolgdsouza** [vuejs-br/vagas#167]
Eiii, essa é para você que quer ser uma das lideranças do time da Contabilizei que está mudando a forma como o brasileiro se relaciona com a contabilidade!

**A nossa missão é democratizar a contabilidade para micro e pequenas empresas de todo o Brasil.** Somos uma empresa de tecnologia que está promovendo a maior revolução da indústria de contabilidade nas últimas décadas. Impactamos positivamente na vida de **mais de 20 mil micros e pequenas empresas de todo país** oferecendo contabilidade online, econômica e inteligente.

O desafio é para ser **Tech Lead Senior na Contabilizei** sendo responsável por definir o backlog técnico junto com o time apoiando desenvolvedores nas entregas de soluções e assegurando as entregas técnicas do time e assim garantir que desenvolvedores estejam integrados e tenham os conhecimentos necessários para desempenhar seu papel.

O que você precisa saber para vir com a gente neste desafio? Experiência com Vue Js, Java (Springboot), Kotlin, Node, microsserviços e monolítico, esteira de DevOps, CI/CD, Kubernetes, Angular e  GIT, BitBucket e ambiente Cloud GCP. 

Contratação **CLT**, remoto em 2020 com retorno **presencial** em 2021.

**Conheça mais sobre essa oportunidade:** https://byintera.in/xq

**Comment by ErickPetru** [comment]
Olá @carolgdsouza, por favor, forneça o conjunto de informações mínimo necessário para ajudar manter a qualidade de nossa comunidade: presencial/remoto, tipo de contratação (CLT/PJ), nível de experiência.

**Comment by ErickPetru** [comment]
Fechando já que a oportunidade foi reaberta em #170.
