### ISSUE TITLE
[Florianópolis-SC] Front-end Vue.js Developer @ Prevision

### ISSUE THREAD

**Issue by danielmaniglia** [vuejs-br/vagas#168]
## Descrição da vaga

Buscamos um profissional que saiba deixar nossos clientes com os olhos brilhando ao utilizar nossa plataforma.
Nosso produto é lindo e nossos clientes são apaixonados por ela. Porém queremos entregar mais, deixa-la ainda mais linda e atraente.
Se você é apaixonado por UX/UI e conheçe muito de Vue.js, vem crescer conosco!

## Local
Essa oportunidade é para atual em Floripa, na ilha da magia na modalidade presencial.

## Benefícios

- Salário atrativo

## Requisitos

Profunda experiência em desenvolvimento de software;
Vivência com Teste unitário;
Conhecer React ou Vue.js;
Experiência com Git;
Clean Code;

**Diferenciais:**
GraphQL.

## Contratação
PJ 

## Nossa empresa
Desenvolvedor de software para a área de construção civil. 
Nosso produto é lindo e nossos clientes são apaixonados por ela. Porém queremos entregar mais, deixa-la ainda mais linda e atraente.
Se você é apaixonado por UX/UI e conheçe muito de Vue.js, vem crescer conosco!

## Como se candidatar

Pelo link:  https://vagas.hunterco.com.br/job/5f3ba02edcd904001b2208bc?r=hmshlf

## Labels
VUE.JS 
PRESENCIAL 
REMOTO
SENIOR
PJ

#### Alocação
- Presencial

#### Experiência
- Sênior

#### Regime
- PJ

**Comment by leonardotessaroalves** [comment]
Manjo mt de Vue pena q eh presencial

**Comment by danielmaniglia** [comment]
Leonardo, conversei internamente e existe a possibilidade de trabalho remoto. Inscreva-se pelo link: https://vagas.hunterco.com.br/job/5f3ba02edcd904001b2208bc?r=hmshlf

> Manjo mt de Vue pena q eh presencial

**Comment by leonardotessaroalves** [comment]
> Leonardo, conversei internamente e existe a possibilidade de trabalho remoto. Inscreva-se pelo link: https://vagas.hunterco.com.br/job/5f3ba02edcd904001b2208bc?r=hmshlf

Show! Já fiz a inscrição. Muito obrigado!

**Comment by d1urno** [comment]
Olá! eu vi que a vaga pode ser remota e tentei me aplicar mas nesse site ta dando erro para mim.
Gostaria de deixar meu CV por [aqui](https://pablomiceli.dev) ou conhecer se ha uma outra forma de aplicar, sendo que também existe a possibilidade de eu morar la em Floripa 👍

**Comment by danielmaniglia** [comment]
> Olá! eu vi que a vaga pode ser remota e tentei me aplicar mas nesse site ta dando erro para mim.
> Gostaria de deixar meu CV por [aqui](https://pablomiceli.dev) ou conhecer se ha uma outra forma de aplicar, sendo que também existe a possibilidade de eu morar la em Floripa 👍

Bom dia, 

Pode enviar o curriculo para daniel.maniglia@parceitohunterco.com.br 

Obrigado.
