### ISSUE TITLE
[São Paulo/SP | Remoto] Vue.js Developer Junior ou Pleno @ Port Louis

### ISSUE THREAD

**Issue by eduardonoronha** [vuejs-br/vagas#176]
Somos uma empresa de tecnologia que desenvolve produtos de RPA com impacto direto nos resultados dos nossos clientes. Possuímos uma sólida base de produtos já em operação e uma carteira importante de backlog.

O nosso front está desenvolvido em vue, acessando uma plataforma de APIs desenvolvida em microsserviços com node.js.

Procuramos desenvolvedores junior ou pleno para implementar novas funcionalidades e fornecer manutenção ao código atual.

Possuímos flexibilidade para trabalho local ou remoto, e forma de contratação CLT ou PJ.

No começo do ano fizemos uma contratação através deste canal, e estamos muito satisfeitos. Estamos expandindo a equipe, por favor envie o currículo para eduardo@portlouis.inf.br caso tenha interesse.

**Comment by ErickPetru** [comment]
Olá @eduardonoronha, tudo bem? Por favor, atualize para informar o nível de experiência desejado para o candidato, para podermos completar os _labels_ da vaga.
