### ISSUE TITLE
[São Paulo/SP] Analista de Desenvolvimento de Sistemas Web Júnior @ ALTHAIA

### ISSUE THREAD

**Issue by rmeira** [vuejs-br/vagas#18]
## Descrição da vaga

Procuramos um perfil apaixonado pelo desenvolvimento web, que sugira novas ideias e soluções e que consiga buscar soluções para problemas de forma proativa no Google.
Irá analisar, criar scripts, dar manutenção e documentar sistemas de back-end e Front-end da empresa, usando as seguintes linguagens: PHP, SQL (PostgreSQL, SQL Server), HTML5, CSS3, Javascript, JQuery e GIT para versionamento de códigos.
Principais responsabilidades (atividades a serem desenvolvidas): 
- Efetuar levantamento de requisitos junto aos clientes. 
- Desenvolver aplicações Web utilizando PHP.
- Prestar suporte técnico relacionado às aplicações web. 
- Contribuir com ideias para enriquecer a experiência do usuário-final.
- Contribuir também com ideias para a padronização do desenvolvimento.

### Áreas de formação
- Analise e desenvolvimento de sistemas
- Sistemas de informação
- Sistemas para internet

## Local

Butantã - São Paulo - ZO

## Benefícios

- Plano de Saúde
- Vale Refeição
- Vale Alimentação
- Vale Transporte

#### Diferenciais

- Apresentar trabalhos pessoais, acadêmicos, experiências de estágios anteriores ou freelancer que ele possa indicar como portfólio.
- Conhecimento em frameworks javascripts como VueJS
- Conhecimento em Laravel Framework

## Contratação

- CLT

## Como se candidatar

Enviar currículo para: vanessa.frederico@althaia.com.br

## Labels

- alocação/Presencial
- experiência/Estágio
- experiência/Júnior
- regime/CLT

**Comment by renatoReboucas** [comment]
Ta em aberto ainda?

**Comment by rmeira** [comment]
Está sim Renato
