### ISSUE TITLE
[São Paulo/SP | Remoto] Front-end Vue.js Developer @ MGB

### ISSUE THREAD

**Issue by fabiofcos** [vuejs-br/vagas#184]
## Descrição da vaga

Você é um expert em seu ofício e um solucionador de problemas implacável. Você pensa criticamente e questiona tudo, buscando um entendimento profundo dos conceitos e dos problemas do negócio. Você é transparente e incansável, compartilhando informações de forma eficiente e construtiva para melhorar o ambiente ao seu redor. Você faz e alcança coisas que a maioria das pessoas acha difíceis, mas é humilde e um colaborador de equipe sólido. E,é claro, está ansioso para aprender cercado por pessoas que lhe darão todo o apoio de que você precisa!

## Local

Remoto ou Escritório, São Paulo/SP

## Requisitos

**Responsabilidades:**
Desenvolvimento Frontend
Manutenção de sistemas para correção de falhas/erros
Preocupação com fidelidade das telas em relação aos protótipos
Boa modularização e reuso de código
Implementação de melhorias
Atuar como parte da equipe ágil e cultura DevOps
Otimizar a aplicação para melhor velocidade e escalabilidade
Garantir a validação dos dados fornecidos pelos usuários
Criar código e bibliotecas reutilizáveis para uso futuro
Atuar no desenvolvimento de aplicações com foco em performance, qualidade e usabilidade
Participar de todas as etapas da criação do produto, desde o planejamento, passando pelo desenvolvimento, até a entrega e documentação
Discutir ideias, ferramentas e metodologias que possam otimizar o desenvolvimento do produto

**Qualificações:**
Base sólida em desenvolvimento frontend e fluência em aplicá-la a problemas práticos
Domínio em JavaScript,  framework Vue.js, com Vuex e Bootstrap para interagir com RestApi
Conhecimento de tecnologias como HTTP, DOM, CSS, HTML5, JSON, etc.
Conhecimento de SOLID, CleanCode e Cultura de teste
Conhecimento em Cypress, Jest, GitHub Actions e Azure DevOps
Conhecimento em bancos de dados relacionais e não relacionais
Conhecimento aplicado de padrões de design modernos
Experiência prática com integração contínua, implantação automatizada e testes
Conhecimento dos princípios ágeis e suas aplicações práticas

**Diferenciais:**
Formação em tecnologia
Inglês técnico
Plataformas de e-commerce (Vtex, Wordpress, Magento, etc.)

## Nossa empresa

Somos movidos pela paixão por inovar e transformar a vida das pessoas pela educação por meio da natação!

Vamos conversar?

## Como se candidatar

Por favor, envie um e-mail para fabiofranco@metodologiagb.com.br com seu CV anexado. Enviar no assunto: _Vaga Vue.js_

#### Alocação
- Flexível

#### Experiência
- Júnior/Pleno

#### Regime
- PJ

**Comment by fabiofcos** [comment]
Pessoal, ainda estamos selecionando!
Essa pessoa estará em um papel chave em nossos projetos, oportunidade bem legal de fazer um trabalho diferenciado e com bastante autonomia.
Basta enviar o CV para se inscrever.

**Comment by wesleybruno** [comment]
Esta vaga ainda está disponivel?

**Comment by fabiofcos** [comment]
Olá, está sim!

Quer me enviar o seu cv?

Abs,
Fabio Franco
