### ISSUE TITLE
[São Paulo/SP] Front-end Vue.js e Vuex Developer @ Ciclic

### ISSUE THREAD

**Issue by andvictor** [vuejs-br/vagas#190]
## Descrição da vaga

Implementar e manter aplicações web, websites, landing pages, blogs, e-mails e protótipos
visando a melhoria constante do produto final;
- Garantir que as aplicações web funcionem em diferentes navegadores e dispositivo;
- Trabalhar junto com o squad para garantir que a melhor solução será implementada;
- Ser responsável pelo desenvolvimento e implantação de melhores práticas para o
desenvolvimento de front-end;
- Se manter atualizado e acompanhar as evoluções e tendências tecnológicas do mercado;
- Proposição de melhorias tecnológicas e processuais;
- Trabalhar em conjunto com o designer de UI/UX para converter wireframes e protótipos em
código;
- Garantir alta qualidade das plataformas e consistência com a marca;
- Integrar soluções de front-end com os serviços de back-end;
- Escrever documentações e guias claros, precisos e funcionais para o front-end;
- Ser referência em front-end e compartilhar conhecimentos com a equipe;
- Estar pronto para, quando necessário, definir estratégias de desenvolvimento, linguagens,
metodologias e ferramentas de front-end;
- Identificar oportunidades e demandas de desenvolvimento, definindo sua priorização e
integração com as demais áreas;
- Gerenciar os recursos tais como: mapeamento de escopo, estimativa, esforço, prazos para
concepção do projeto, até a entrega final dos projetos garantindo o escopo e prazos
acordados;

## Local

Remoto durante a pandemia posteriormente no  Escritório, São Paulo/SP - Vila Olimpia

## Benefícios
Plano de saúde
Plano odontológico (opcional)
Seguro de vida
Vale refeição – 827,42
Vale alimentação – 585,09
Vale transporte (opcional)
Auxílio creche / Babá
Plano de previdência (opcional)
Gympass
Bônus anual de até 3 salários (limitado a performance da companhia e do funcionário)
Diferenciais
Horário de trabalho flexível
Home office 1 vez por semana
Day Off de aniversário

## Requisitos

Habilidades imprescindíveis:
- Experiência em Vue e Vuex;
- Experiência com SPA;
- Domínio em HTML, CSS e JavaScript;
- Metodologias CSS (BEM, Atomic, OOCSS, ...);
- Pré-processadores CSS (Sass, PostCSS, Less, ...);
- Entender como o Browser funciona;
- Conhecer HTTP, HTTP/2 e APIs Rest;
- Testes automatizados (Jest, Jasmine, Selenium);
- Controle de versão Git;
- Criação de código limpo, legível, cross-browser e cross-device;
- SEO;
- Performance;
- Design pattern em javascript;
- Scrum;

Habilidades Desejáveis:
- Arquitetura front-end;
- Micro front-end;
- Acessibilidade;
- ES6 / ES7;
- Webpack;
- CI\CD;
- Design System;
- Docker;

## Contratação

CLT a combinar.

## Nossa empresa

A Ciclic é uma empresa brasileira, 100% digital, que nasceu em novembro de 2017 para oferecer ao cliente uma plataforma de proteção completa, com soluções digitais de seguros, serviços e previdência.

Descomplicamos o universo desses produtos para que você comece hoje a proteger seu presente e planejar o seu futuro com  transparência , confiança e o melhor custo/benefício do mercado.

## Como se candidatar

Por favor, envie um e-mail para anderson@mazza.tech com seu CV anexado. Enviar no assunto:  Vaga Ciclic Front end Vue

#### Experiência
- Pleno
- Sênior

#### Regime
- A-Combinar
- CLT

**Comment by ErickPetru** [comment]
Apenas para deixar clara para o autor a mudança, vagas remotas apenas durante a pandemia não são vagas remotas definitivas (pessoas de longe não irão se candidatar).
