### ISSUE TITLE
[Ribeirão Preto/SP | Remoto] Front-end Vue.js Developer @ FINX

### ISSUE THREAD

**Issue by KevinMarcelOriginal** [vuejs-br/vagas#199]
## Descrição da vaga

Vaga para atuar em StartUp que junto da Dryve, esta transformando o mercado de veículos através da tecnologia!

## Local

Remoto ou Escritório, Ribeirão Preto/SP

#### Diferenciais

- Horário Flexível
- Construção de produto novo no mercado!

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com desenvolvimento Vue.js ou REACT
- Experiência com GIT e GITFlow;
- Vivência ou aptidão em atuar em ambiente que desenvolve com metodologias ágeis

**Desejáveis:**
- conhecimento em alguma linguagem de programação Back-End; 
- Conhecimento em alguma linguagem de programação Funcional. 

## Contratação

PJ a combinar.

## Nossa empresa

Aqui na Corporação XPTO somos líderes em...

**Aqui usamos:**
- Vue.js
- React
- Flutter (Mobile)
- Java (Back-End)
- Kotlin (Back-End)

## Como se candidatar

Por favor, envie um e-mail para kevin.marcel@dryve.com.br com seu CV anexado. Enviar no assunto: _Vaga Vue.js_

#### Alocação
- Flexível
- Presencial
- Remoto

#### Experiência
- Pleno
- Sênior

#### Regime
- PJ

**Comment by ErickPetru** [comment]
Olá @KevinMarcelOriginal, na última vaga que vocês postaram por aqui em junho, você me informou que tratava-se da migração de um sistema em Vue.js para React. Se este for o caso novamente, sugiro que atualize a vaga para deixar explícito, assim desenvolvedores que preferem trabalhar especificamente com Vue.js não correrão o risco de se candidatar incorretamente.
