### ISSUE TITLE
[Itajaí/SC | Remoto] Front-end Vue.js Developer @ We Dev Tecnologia

### ISSUE THREAD

**Issue by adeildo-jr** [vuejs-br/vagas#205]
## Descrição da vaga

Essa vaga é voltada para construção de API's e integração à API's de parceiros.

## Local

Itajaí/SC ou Remoto

## Benefícios

- Participação nos resultados
- Flexibilidade de horário
- Ajuda de custo para aulas de inglês
- Ajuda de custo para mudança de cidade, caso deseje se mudar para a cidade do escritório
- Gosta de pizza ou lanche? Vamos mandar um vale-lanche para você mensalmente

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento JavaScript
- 2 anos de experiência com desenvolvimento Vue.js
- HTML5, JS, CSS
- Conhecer os design systems mais famosos: Bootstrap, Material Design

**Desejáveis:**
- Conhecimentos em Vuex
- Conhecimentos em API's
- Inglês
- TDD
- Conhecimento em metodologias ágeis
- Se você é uma pessoa pro-ativa e comunicativa, é um extra também ;)

**Diferenciais:**
- Temos diversos OSS no qual é voltado a manter pacotes de integração a parceiros e no desenvolvimento do ecossistema de criptografia e blockchain.

## Contratação

PJ a combinar.

## Nossa empresa

Somos uma Software House que desenvolve tecnologias inovadoras. Criamos soluções de pagamentos, especialistas em blockchain e open banking.
Quer mudar a forma de como usamos o dinheiro? Então venha fazer parte da nossa equipe!

**Aqui usamos:**
- Vue.js
- PHP
- Python
- Ruby
- Flutter
- React Native
- Docker

## Como se candidatar

Por favor, acesse o link e preencha o formulário para se candidatar na vaga: https://docs.google.com/forms/d/e/1FAIpQLSeUfSPV1t9yaD_rBIk9WZm--DtZgEfesp8pUJqeX3VAQv1zdQ/viewform

#### Alocação
- Flexível
- Presencial
- Remoto

#### Experiência
- Pleno

#### Regime
- PJ a combinar

**Comment by maarkN** [comment]
o titulo diz ser Front-end, mas o formulário está para Back-end...

**Comment by adeildo-jr** [comment]
> o titulo diz ser Front-end, mas o formulário está para Back-end...

@maarkN havia colado o link errado, corrigi aqui. Obrigado por informar
