### ISSUE TITLE
[Cascavel/PR] Front-End Developer no Focus Concursos

### ISSUE THREAD

**Issue by lc-brito** [vuejs-br/vagas#21]
# Descrição da vaga
Desenvolvimento de soluções para a área de educação, em PHP (Laravel) e JavaScript (Vue).

# Local
Remoto ou Cascavel/PR.

# Requisitos
**Obrigatórios**
- Experiência com HTML5, CSS3 e pré-processadores.
- Experiência no desenvolvimento com javascript [ES5, ES6].
- Experiência com aplicações SPA.
- Experiência com APIs Restful.
- Experiência em algum Framework baseado em componentes (Vuejs, React, Angular).
- Experiência com Git.
- Experiência com Vue.
- Capacidade de trabalhar em equipe (pró-ativo).

**Diferencial**
- Conhecimento em PWA.
-  Conhecimento prático sobre SOLID, clean code, refactoring e testes automatizados.
-  Conhecimentos básicos de Laravel 5 ou outro framework PHP MVC.
-  Conhecimentos em UX.

# Contratação
PJ a combinar.

# Como se candidatar
Envie seu LinkedIn, GitHub, CV, Contato, Email para luis@grupofocus.com.br com o assunto Vaga Back-End.

# Tempo médio de feedbacks
Costumamos entrar em contato em até 01 dia após receber seu contato.

# Labels
- PJ
- Sênior
- Pleno
- PHP
- API,
- Vue
- SPA

**Comment by assuncaojr** [comment]
Qual seria o provento oferecido?

**Comment by lc-brito** [comment]
Bom dia.
O valor de proventos é de R$ 3000,00, podendo ser mais se tiver experiência em todos os quesitos da vaga.
________________________________
De: Assunção Jr <notifications@github.com>
Enviado: terça-feira, 19 de março de 2019 10:44
Para: vuejs-br/vagas
Cc: Luis; Author
Assunto: Re: [vuejs-br/vagas] [Cascavel/PR] Front-End Developer no Focus Concursos (#21)


Qual seria o provento oferecido?
