### ISSUE TITLE
[Remoto | Goiânia/GO] Full-Stack Developer @ Work In Ideas - WiiD

### ISSUE THREAD

**Issue by chgyn** [vuejs-br/vagas#215]
# Descrição da vaga

O candidato deverá estar capacitado a:
 - Executar projetos de desenvolvimento envolvendo Framework Laravel PHP
 - Ser capaz de executar projetos de desenvolvimento de interface usando VueJS ou ReactJS
 - Implementar sistema web / API Rest utilizando o framework Laravel PHP

#### Conhecimentos necessários: 

 - PHP
 - Laravel
 - MySQL / PostgreSQL
 - HTML5
 - CSS
 - Javascript
 - VueJS ou ReactJS 
 - API/Rest

#### Diferenciais:
 - Experiência com desenvolvimento utilizando Laravel PHP, VueJS
 - Laravel PHP
 - React Native
 - SCRUM

Experiência com desenvolvimento front-end utilizando como base:
 - Laravel PHP
 - ReactJS
 - VueJS
 - Conhecer e saber como lidar em times que executam SCRUM

## Local

Sede física da empresa, Alpha Coworking (Av. T-1, 2266 - St. Bueno, Goiânia) - (remoto)

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento front-end 

**Desejáveis:**
- conhecimentos em Laravel PHP
- conhecimentos em API Rest
- Scrum

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para contato@wi-id.com com seu CV anexado - enviar no assunto: Vaga Front-End

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by ErickPetru** [comment]
Olá @chgyn, favor não marcar como remoto vaga que exige comparecimento presencial em modelo híbrido. Este _label_ serve justamente para informar o potencial candidato de que pode concorrer à vaga mesmo estando geograficamente distante da cidade em questão, o que não é verdade para esta vaga.

**Comment by chgyn** [comment]
@ErickPetru Olá então essa vaga e remota escrevi errado acabei colocando híbrido / presencial, mas temos disponibilidade para execução remota também.  já removi do texto.
