### ISSUE TITLE
[São Paulo] Vue.js Developer na Accenture

### ISSUE THREAD

**Issue by manoel-freitas** [vuejs-br/vagas#22]
## Descrição da vaga

A gente ta com um projeto gigantesco pra mudar um ecommerce de uma empresa cliente que ta usando jsp pra Vue, e pra isso a gente ta usando NUXT com SSR. Mas você não precisa entender de Nuxt ou de SSR pra se aplicar, se você ja sabe vue ou quer aprender vue e sabe um pouco de JS HTML e CSS e o mais importante quer aprender tudo isso se aplica que vamos mudar tudo isso juntos

## Local

Zona Sul de SP, São Paulo -  Morumbi

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 28/dia
- Auxílio creche
- Dentre outros

#### Diferenciais

- Uma maquina super potente
- Sexta de cerveja
- Sala de jogos
- Horário flexível

## Requisitos

**Obrigatórios:**
- Tenha vontade de aprender 
- Tenha conhecimentos básicos de HTML, CSS e JS

**Desejáveis:**
- Saiba algum framework como Angular, React e Vue
- conhecimentos em Atomic Design

## Contratação

CLT Presencial com salário entre 3k à 4,5k

## Nossa empresa

Aqui na Accenture temos um otimo plano de carreira e lideres que realmente querem que você cresça, com participação nos lucros e mentores para te ajudar a entender como funciona essa grande empresa de 430 mil funcionários espalhados pelo mundo. Você vai ter ótimas oportunidades para aprender e crescer em sua carreira. 

## Como se candidatar

Por favor envie um email para manoel.jose.de.neto@accenture.com com seu CV anexado - enviar no assunto: Vaga Vue.js

## Labels

- alocação/Flexível
- alocação/Presencial
- regime/CLT

**Comment by IgorHalfeld** [comment]
Deu bom? @manoel-freitas haha

**Comment by adamsalves** [comment]
Da tempo de enviar ainda? Agora que vi a vaga... :)

**Comment by manoel-freitas** [comment]
Na verdade não deu pra receber mais currículos foi uma falha minha eu abri quando o pessoal do rh já tinha fechado e quando mandei tomei um leve esporro haha mas quem conseguiu enviar (que foram dois) tão sendo avaliados

**Comment by manoel-freitas** [comment]
Perdão pela vergonha que passei ><
