### ISSUE TITLE
[Remoto] Desenvolvedor Vue.js Pleno @ Cogna Tecnologia da Informação

### ISSUE THREAD

**Issue by rmarasciulo** [vuejs-br/vagas#222]
## Descrição da vaga

Oportunidade para desenvolvedor frontend VueJS. Implementação e manutenção de frontend de aplicações Web e mobile a partir da interpretação de especificações funcionais e de design, consumo e integração de APIs REST, construção e manutenção de modelos de componentes. Realização de testes unitários, correções e refatoramento. Propor e desenvolver soluções para necessidades funcionais e não funcionais do frontend.

## Local
100% Remoto

## Benefícios
- Horário flexível
- Cursos online
- Oportunidade de aprendizado

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento JavaScript;
- Experiência com desenvolvimento Vue.js;
- Experiência com tecnologias correlatas ao VueJS como VueX, VueRouter, Nuxt, Vuetify, Axios e Cypress;
- Experiência com sistemas baseados em REST-API;
- Experiência com Git;

**Desejáveis:**
- Experiência em aplicações no estilo SPA/PWA;
- Conhecimento em pré-processadores CSS;
- Conhecimento de Vue Native;
- Experiência em desenvolvimento mobile;
- Conhecimento de TypeScript.

**Diferenciais:**
- Conhecimentos em alguma tecnologia de backend como Nodes/Express, PHP/Laravel ou Python/Django;
- Conhecimento em alguma cloud como AWS, Heroku, Azure, etc..

## Contratação

PJ. A combinar conforme disponibilidade e experiência.

## Nossa empresa

Somos uma casa de software focada no desenvolvimento de soluções para medicina e orientada por especialistas nessa área. Desenvolvemos soluções web, mobile, IoT, ML e BI oferecidas como serviços para clínicas, centros de diagnóstico e consultórios.

**Aqui usamos:**
- Java Script
- Vue.js
- Python
- PostgreSQL
- Azure

## Como se candidatar

Por favor, envie seu CV para rh@cognait.com.br. Certificações e comprovantes acadêmicos e de cursos são bem-vindos. Colocar no assunto: ‘Dev Frontend Vue’

#### Alocação
- Flexível
- Remoto

#### Experiência
- Pleno
- Sênior

#### Regime
- PJ

**Comment by victorhsantiago** [comment]
Olá, apenas contratação PJ?

**Comment by rmarasciulo** [comment]
Boa tarde Victor,

Sim, somente PJ.

Att.
Ricardo

Em sex., 15 de jan. de 2021 às 17:25, Victor Santiago <
notifications@github.com> escreveu:
