### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) FullStack Pleno @ Instituto ABCD

### ISSUE THREAD

**Issue by victorhvs-iabcd** [vuejs-br/vagas#236]
## Descrição da vaga

Desenvolvedor(a) FullStack Pleno que tenha domínio em HTML, CSS, Javascript e conhecimento em VueJS e Firebase. Será solicitado a criação de novas aplicações, bem como manutenção de aplicações existentes.

## Local

Presencial, São Paulo/SP - Pinheiros

## Benefícios

- VR
- Bonus

## Requisitos

**Obrigatórios:**
- Formação em ensino superior ou técnico relacionado a TI.
- No mínimo 2 anos de experiência em desenvolvimento web;
- Projetos publicados em NodeJS.
- Domínio em Javascript, CSS e HTML;
- Conhecimento em NodeJS;
- Conhecimento em metodologias ágeis (Scrum/Kanban);
- Inglês Técnico;
- Experiência com ferramentas de versionamento de código (GIT,...);
- Conceitos de Banco de Dados NoSql;
- Habilidades interpessoais de escrita e de comunicação verbal;

**Desejáveis:**
- Conhecimentos em Vuex
- Conhecimentos em Firebase

**Diferenciais:**
- Projetos open-source

## Contratação

Regime PJ, até R$6.000,00.

## Nossa empresa

O Instituto ABCD é uma organização social que se dedica, desde 2009, a gerar, promover e disseminar projetos que tenham impacto positivo na vida de brasileiros com transtornos específicos de aprendizagem através de ferramentas e matérias inovadores.

**Aqui usamos:**
- Vue.js
- Firebase
- NodeJs

## Como se candidatar

Por favor, envie um e-mail para vsousa@institutoabcd.org.br com seu CV anexado. Enviar no assunto: _Vaga Vue.js_

#### Alocação
- Presencial

#### Experiência
- Pleno

#### Regime
- PJ

**Comment by VictorHVS** [comment]
A vaga permanece aberta.
