### ISSUE TITLE
[São Paulo/SP] Desenvolvedor Front-End @ Radar Profissional

### ISSUE THREAD

**Issue by RADARProfissional** [vuejs-br/vagas#24]
DESENVOLVEDOR FRONT-END

Local: Vila Leopoldina/SP
Contrato PJ - 7 dias de descanso remunerado por semestre
Horário flexível

São requisitos obrigatórios: HTML5, CSS, Java   Script e Vue JS Framework           São requisitos desejáveis: Designer e automação de testes               Superior Completo em Tecnologia da Informação ou Exatas.     Experiência mínima de 2 anos desenvolvendo soluções em DotNet utilizando as   ferramentas acima.

Enviar analista@radarprofissional.com.br

**Comment by IgorHalfeld** [comment]
Consegue dar mais info?

**Comment by RADARProfissional** [comment]
VAGA: DESENVOLVEDOR FRONT END JUNIOR

 

Requisitos:  

·         Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;

·         Imprescindível experiência anterior atuando com HTML5, CSS, Java Script e Vue JS Framework;

·         Será considerado como diferencial, o profissional com experiência em Designer e automação de testes. 

 

 

Contratação: PJ

Local: São Paulo/SP 

 

 

 

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: Igor Luiz Halfeld [mailto:notifications@github.com] 
Enviada em: sexta-feira, 12 de abril de 2019 11:24
Para: vuejs-br/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Author <author@noreply.github.com>
Assunto: Re: [vuejs-br/vagas] [São Paulo] Front-End [Radar Profissional] (#24)

 

Consegue dar mais info?
