### ISSUE TITLE
[REMOTO] Vue.JS Developer na Citar.Tech

### ISSUE THREAD

**Issue by meneguite** [vuejs-br/vagas#25]
### O que nós buscamos
* Responsável por desenvolver, testar e documentar rotinas;
* Atuar em implementações, melhorias de performance e integrações; 
* Desenvolver códigos bem estruturados utilizando boas práticas de programação;
* Realizar revisão por pares dos artefatos de programação; 
* Interagir com todo o time Scrum de forma construtiva na busca por resultados que agreguem valor aos clientes; 
* Construir código com testes automatizados/unitários para garantir a qualidade.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- VueJs 2;
- HTML, CSS, SASS;
- Javascript ES6;
- Consumo de Rest APIs;
- Noções básicas de scrum e metodologias ágeis;
- Domínio do Git para versionamento de projetos;

**Desejáveis:**
- Conhecimentos em Vuex
- Experiência com testes unitários usando Mocha;

**Diferenciais:**
- Experiência na utilização do docker;

## Contratação
PJ

## Como se candidatar

Após a execução do teste disponível em https://github.com/citartech/job-vacancies/blob/master/frontend-vue.md envie um email para rh.dev@grupocitar.com.br com seu CV anexado ou link do linkedin - enviar no assunto: Vaga Front-End

## Outras vagas abertas

Além dessa vaga de backend temos mais duas vagas uma de full stack e uma de front, caso tenham interesse podem visualizar mais detalhes nos repositórios abaixo:

> Backend: https://github.com/citartech/job-vacancies/blob/master/backend-node.md
> Fullstack: https://github.com/citartech/job-vacancies/blob/master/fullstack-js.md

## Labels

- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/PJ

**Comment by wesleysd1989** [comment]
segue uma crítica construtiva, disponibilize a informação de um salario base ou um teto salarial, pois, dedicar um tempo efetuando um teste prático as cegas e no final enviar o teste com a pretensão salarial, sem ter noção alguma se vai ser recusado pela pretensão fica complicado.

**Comment by wouerner** [comment]
Vaga continua aberta?

**Comment by meneguite** [comment]
Continua sim @wouerner ..

**Comment by wouerner** [comment]
Desculpe a demora, acabei não vendo a resposta. Fiz o teste, e enviei hoje pelo e-mail solicitado.

**Comment by meneguite** [comment]
Obrigado a todos que fizeram a submissão para a vaga, ainda que tenhamos algumas vagas em aberto, em respeito aos que já enviaram vou fechar a issue para que consigamos colocar as submissões já enviadas em dia.
