### ISSUE TITLE
[Remoto] Fullstack Developer (PHP Laravel / VueJs) @ Guide121

### ISSUE THREAD

**Issue by gabrielhws** [vuejs-br/vagas#291]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url https://coodesh.com com o pop-up personalizado de candidatura. :wave:
<p></p>
<div style="text-align:none;"><img src="https://cdn.discordapp.com/attachments/775782208061308979/806999152059613194/carbon_1.png" alt="undefined" style="height: auto;width: auto"/></div>
<p></p>
<p>A Guide121 nasceu com o propósito de transformar o turismo a partir da tecnologia. Levamos inteligência artificial para experiência do cliente via CHATBOTs. Atuamos com parques, resorts, hotéis e entretenimento. Conseguimos otimizar processos, reduzir custos além de gerar vendas diretas através de uma plataforma com diversas funcionalidades ao cliente como disparo de mensagens ativas, agendamentos, gestão de conteúdo, além de chatbots com amplo conhecimento no turismo capaz de acompanhar a jornada de ponta a ponta!</p>
<p></p>
<p>Estamos em busca de um Desenvolvedor FullStack Pleno/Senor que esteja pronto e disposto para atuar com uma Startup em fase de crescimento e expansão, em um ambiente dinâmico, intenso, que o aprendizado e conhecimento também é acelerado!&nbsp;</p>

## Guide121: 
 <p>A Guide121 nasceu com o propósito de transformar a forma de dar assistência a partir da tecnologia. Levamos inteligência artificial para experiência do cliente. Atuamos com parques, resorts, hotéis e entretenimento. Conseguimos otimizar processos, reduzir custos além de gerar vendas diretas através de chatbots com amplo conhecimento no turismo capaz de acompanhar a jornada de ponta a ponta!&nbsp;</p>
</p>

 ## Habilidades: 
 - API 
- Chatbot 
- Laravel 
- MongoDB 
- PHP 
- PostgreSQL 
- Vue.js 
- Node.js 
- PHPUnit
## Local: 
 100% Remoto
## Requisitos: 
 - Sólidos conhecimentos com php 
- Conhecimentos com Laravel 
- Docker 
- Queue (rabbitMQ, SQS, Beanstalk, redis) 
- Test (Unit, Acceptance) 
- Experiência com api design 
- PostgreSQL, MySQL, MongoDB, DynamoDB 
- Linux (basic for work) 
- Html, Css, JavaScript, Git 
- VueJS 
- NPM / Yarn 
- Less / Sass 
- Desejável inglês

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer (PHP Laravel / VueJs) na Guide121](https://coodesh.com/vagas/fullstack-developer-003849?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by ErickPetru** [comment]
@gabrielhws por gentileza, siga o _template_ da comunidade para os títulos das vagas. Toda vaga da Coodesh que você posta eu preciso editar o título.
