### ISSUE TITLE
[Salvador/BA | Remoto] Front-end Vue.js Developer @ nTopus

### ISSUE THREAD

**Issue by aurium** [vuejs-br/vagas#296]
## Descrição da vaga

Construir e otimizar a experiência do usuário e nossas funcionalidades para ajudar a entregar simplicidade e um universo de novas possibilidades aos nossos clientes. Irá atuar em conjunto com os outros profissionais do time, implantando novos recursos, migrando código legado, escrevendo testes e demais atividades relacionadas.

<img src="https://user-images.githubusercontent.com/30254/119900798-64bc0d00-bf1b-11eb-8635-51ee073d680e.png" align="right" width="400" alt="Front-end Vue.js Developer @ nTopus">

## Local

Remoto ou Escritório, Salvador-BA

## Benefícios

- Plano de saúde e odontológico;
- Auxílio home-office para aquisição de acessórios;
- R$ 1.200,00 a R$ 2.000,00 em benefícios flexíveis;
- Livros e Cursos.

#### Diferenciais

- Home office mesmo após a pandemia;
- Escritório físico para os que desejarem;
- Aula de Inglês;
- Sem dress-code;
- Day off;
- Happy Hour.

## Requisitos

**Obrigatórios:**
- Conhecimentos em Javascript (ES6);
- Conhecimentos em HTML5, CSS3;
- Conhecimentos em estruturas conteinerizadas (Docker);
- Conhecimentos em testes de software;
- Conhecimentos em sistemas de versionamento de código (git, Hg (Mercurio), SVN, etc).

**Desejáveis:**
- Ter trabalhado com APIs REST;
- Ter trabalhado com frameworks e libs de terceiros;
- Ter trabalhado com estrutura de micro-serviços;
- Saber trabalhar com Websocket;
- Conhecimentos sobre kubernetes;
- Linux;
- Boas práticas de Log/auditoria;
- Métricas na aplicação;
- Conhecimentos em Typescript;
- Conhecimento em VueJs.

## Contratação

CLT R$ 4.000,00 a 6.000,00, dependendo do nível do candidato.

## Nossa empresa

A [nTopus](https://www.ntopus.com.br/) é uma startup de tecnologia que desenvolve soluções que melhoram a segurança das pessoas e aumentam a eficiência dos processos em tempo real a partir da transmissão de dados sobre múltiplos meios de comunicação, principalmente os rádios de comunicação de voz, que são obrigatórios em qualquer ambiente de missão crítica. Nossas soluções de software realizam a integração com dispositivos de tecnologias distintas a exemplo de tag’s de IoT, rádios digitais, smartphones, câmeras com vídeo analítico e outros sensores e atuadores industriais.

**Aqui usamos:**
- Vue.js
- Typescript
- Go
- Python
- Docker
- Kubernetes
- e coisas que você nunca viu...

## Como se candidatar

Por favor, Envie o seu currículo para comercial@ntopus.com.br com o assunto: _Vaga Frontend_

#### Alocação
- Flexível
- Presencial
- Remoto
(sim, todas são válidas e permanecerão após a pandemia)

#### Experiência
- Júnior
- Pleno

#### Regime
- CLT
- PJ

**Comment by hallss93** [comment]
possibilidade de PJ?

**Comment by Cosmess** [comment]
CV enviado!

**Comment by aurium** [comment]
Acabamos de concluir a seleção, mas sintam-se convidadas e convidados a enviar o CV a qualquer momento, caso tenham interesse na proposta da nTopus.
