### ISSUE TITLE
[Remoto] Front-end Vue.js Developer @ DOMVS

### ISSUE THREAD

**Issue by thaisvilladal** [vuejs-br/vagas#299]
## Descrição da vaga

Projeto bacana com Vue.js em projetos bem inovadores.

## Local

Remoto 
Aceitamos candidatos de todo o Brasil

## Benefícios

- Plano de saúde
- Plano Odontológico
- Vale Refeição

## Requisitos

**Obrigatórios:**
• Conhecimento/experiência com desenvolvimento front-end - Vue.js, JavaScript, HTML 5;
• GIT;
• Maven;
• Conhecimento em banco de dados relacional

**Desejáveis:**
• Conhecimento em back-end: PHP/.NET/Java 8 ou 1;
• Spring framework e Python.

## Contratação

CLT ou PJ - remuneração em aberto.

## Nossa empresa
Somos uma consultoria de TI focada em oferecer excelência aos nossos Clientes e desenvolvimento aos nossos Colaboradores, através de soluções, pessoas e processos pensados para cada necessidade de negócio. Buscamos e valorizamos as relações sólidas e a transparência nas ações como nosso maior patrimônio. 
Temos mais de 7 anos no mercado de TI, prezamos pelo engajamento, desenvolvimento e acolhimento das pessoas que trabalham em nosso time.
Buscamos profissionais com sede de tecnologia, que curta muuuito novos desafios e que seja apaixonado pelo que faz! 

## Como se candidatar

Por favor, envie um e-mail para thais.villadal@domvs.com.br com seu CV anexado. Enviar no assunto: Vaga Vue.js

#### Alocação
- Remoto

#### Experiência
- Júnior
- Pleno

#### Regime
- A-Combinar
- CLT
- PJ

**Comment by JoaoPauloRamosLopes** [comment]
A vaga ainda está aberta e é necessário ter experiência prévia ?
