### ISSUE TITLE
[Bahia - Teixeira de Freitas] Front-End Developer na [Inovatto Sistemas]

### ISSUE THREAD

**Issue by Gildarth** [vuejs-br/vagas#3]
## Descrição da vaga
Estamos com vagas abertas no time de Desenvolvimento! Buscamos pessoas que tem grandes ideias e vontade de construir algo incrível. 

Se você é um desenvolvedor Front-end acima da média ou conhece alguém, essa é a oportunidade!

## Local
Escritório Teixeira de Freitas - Extremo Sul da Bahia (Possibilidade ser via Remoto.)

## Requisitos
- Vue.js 2.0
- Quasar Framework 
- HTML5/CSS3
- ECMAScript 6 (ES6)
- Consumo de APIs (RESTfull)
- Conhecimento com Git

## Contratação
A combinar

## Rendimentos
R$ 3.000,00 ao mês

## Nossa empresa
Somos uma Startup inovadora pronta para oferecer uma nova experiência ao mercado que mais cresce no mundo. Conectamos: Gente boa + Empatia + Novas ideias + Design + Tecnologia.

Para que possamos implementar soluções disruptivas e diferenciadas para simplificar e gerar valor na gestão do negócio de Beleza e Bem-estar utilizamos como base o Project Thinking, Gestão Visual, Agilidade, Neurociência Aplicada e PESSOAS! 

Somos o novo, mas com experiência de gente grande, nasce em 2017 a inovatto sistemas, com o apoio e a experiência da consolidada ECosmetics International Salon presente no Brasil, além da América do Norte, Europa, África e Emirados Árabes e a HSB Hair School Business, premiada com o título de Melhor Escola do Mundo para Cabeleireiros no Hairworld Global Awards em Paris.

## Como se candidatar
Aplique-se pelo link e envie seu currículo para nós: http://www.inovattosistemas.com/carreira/ - Enviar no assunto: Vaga Desenvolvedor Front-end

**Comment by Gildarth** [comment]
Vaga Persiste em aberto.

**Comment by Gildarth** [comment]
Oportunidade em aberta!!

**Comment by Gildarth** [comment]
Oportunidade em aberta!!

**Comment by Gildarth** [comment]
Oportunidade em aberta!!

**Comment by Gildarth** [comment]
Oportunidade em aberta!! Vamos construir juntos um grande negocio!

**Comment by ErickPetru** [comment]
Olá @Gildarth, a vaga está aberta há algum tempo e não sei se tem relação com isto, mas observei que o formulário existente no endereço https://www.inovattosistemas.com/carreira/ não está funcionando, registrando erros no _console_ ao tentar submeter. Avisa o pessoal aí para dar uma verificada. 😉

**Comment by Gildarth** [comment]
Grato! Já encaminhei para equipe de desenvolvimento. 

 

De: Erick Eduardo Petrucelli [mailto:notifications@github.com] 
Enviada em: terça-feira, 21 de maio de 2019 12:53
Para: vuejs-br/vagas <vagas@noreply.github.com>
Cc: Gildarth <ceo@inovattosistemas.com>; Mention <mention@noreply.github.com>
Assunto: Re: [vuejs-br/vagas] [Bahia - Teixeira de Freitas] Front-End Developer na [Inovatto Sistemas] (#3)

 

Olá @Gildarth <https://github.com/Gildarth> , a vaga está aberta há algum tempo e não sei se tem relação com isto, mas observei que o formulário existente no endereço https://www.inovattosistemas.com/carreira/ não está funcionando, registrando erros no console ao tentar submeter. Avisa o pessoal aí para dar uma verificada. 😉
