### ISSUE TITLE
[Remoto] Front-end Vue.js Developer @ Ommed

### ISSUE THREAD

**Issue by Karinemoreira** [vuejs-br/vagas#301]
## Descrição da vaga

Projeto para atuar em Startup dedicada a assistência a saúde.

## Local

Remoto

## Descrição
Como nossa(o) Desenvolvedor(a) Vue.JS você: 

-Irá pensar muito sobre lógica e linguagens de programação;
-Irá explorar o comportamento da Web e seus padrões; 
-Irá desenvolver aplicações utilizando JavaScript; 
-Irá atuar na manutenção dos sistemas desenvolvidos; 
-Irá atuar no desenvolvimento e definição de novas features;
-Irá propor e implementar melhorias nos processos e arquitetura da aplicação; 
-Irá planejar, arquitetar, especificar e implementar soluções baseadas em tecnologia Web; 
-Irá fazer análise, avaliação técnica e estimativa de esforço para desenvolvimento de soluções e funcionalidades; 
-Irá garantir a qualidade dos seus entregáveis, se comprometendo com prazos estipulados e níveis de qualidade de código acertados;
-Irá codificar e realizar testes; 

## Benefícios
-Além de trabalhar com tecnologia de ponta você vai ter a possibilidade de aprender e ensinar todos os dias;
-Salário Compatível 
-Possibilidade de Prêmios sobre os resultados e fazer parte do grupo de sócios;
-Contratação como CLT 
-Trabalho Remoto;
-Bônus por produtividade;

## Requisitos (nem todos obrigatórios)
Conhecimentos e Experiências em Vue.JS, JavaScript,  SQL, NoSQL, Arquitetura de projeto, Google Cloud, NPS, Testes Unitários,  Integração de Sistemas,  APIs,  Gitlab, ClickUp.

-Não é necessário ter graduação, mas é necessário ter conhecimento e capacidade de fazer. 
-Você terá um Bônus: Se estiver cursando ou já estar graduado ou com experiência de trabalho na área.
-Domínio de JS e atenção constante às discussões ocorrendo sobre este mundo;
-Ganha Pontos: Saber gRPC;

- Deve ser naturalmente empático. Você sempre deseja ter empatia com colegas, clientes e usuário final para entender o que estes precisam? 
- Você um bom solucionador de problemas?
- Você pensa na estratégia? 
- Gosta de pensar em desafios complexos e na beleza da entrega de produtos e se preocupa em resolver o problema certo da forma mais agradável possível?;
- Você auto dirigido, auto didata e organizado, líder si mesmo? 
- Queremos alguém que fique confortável com opiniões e direcionamentos que ajudam sempre a criar algo melhor
- Está disposto a se entregar e a fazer a sua parte do time não medindo esforços para que a empresa cresça e você cresça junto?
- Desejar um dia ser um dos sócios da empresa e lutar junto para que as soluções desenvolvidas progridam e se tornem relevantes?
- Querer nos ajudar a fazer o mundo um lugar melhor, de empresas melhores, de serviços melhores com experiencias e pessoas melhores?

## Como se candidatar
[Clicando aqui](https://www.recrutasimples.com.br/vaga/desenvolvedora-frontend-web-vuejs/florianopolis-sc/-MbbwRX3rC_VBCIOSQ2o?referrer=selfShareUrl)

#### Alocação
- Remoto

#### Experiência
- Júnior
- Pleno

#### Regime
- CLT

**Comment by Khurshidbek-Urayimov** [comment]
hello my love girls
