### ISSUE TITLE
[Rio de Janeiro/RJ] Desenvolver Vue.js @ Estante Virtual

### ISSUE THREAD

**Issue by ebertti** [vuejs-br/vagas#33]
Mais informações das vagas:

https://github.com/estantevirtual/vagas

## Sobre nós

A [Estante Virtual](https://estantevirtual.com.br) é o maior portal de compra e venda de livros usados
e seminovos do Brasil, reunindo mais de 16.5 milhões de livros dos melhores sebos e livreiros do país.

A empresa é líder absoluta no setor desde a sua fundação em 2005
e orgulha-se de oferecer ótimas condições de desenvolvimento criativo à sua equipe.  

O fluxo de clientes que a Estante Virtual recebe diariamente
é resultado direto da qualidade desse trabalho: são mais de 10 mil livros vendidos por dia
(top3 na internet brasileira), com um índice de satisfação superior a 97%.

Pensar qualidade, bibliodiversidade e preço é pensar Estante Virtual. Venha trabalhar conosco!

## Nossa Cultura

Comprometimento, qualidade e alegria são nosso DNA. Ambiente descontraído sem esquecer de nossas
entregas e qualidade. Conseguimos dominar a cultura do trabalho remoto e executamos com muita
assertividade os rituais do desenvolvimento ágil com Scrum.

## Vagas

Para ocupar nossas vagas buscamos pessoas interessadas em trabalhar com as mais novas tecnologias,
aprender novas técnicas e métodos de trabalho. Focando sempre em entregas com qualidade.

## Estágios:

Independentemente das vagas, é necessário apenas ter alguma experiência com linux, docker e git,
além de saber alguma linguagem de programação como Python, Javascript ou Ruby.

Buscamos pessoas interessadas em aprender e desenvolver seu conhecimento utilizando nossos desafios para alavancar sua experiência. Entenda a descrição das vagas como o que você aprenderá enquanto estiver estagiando conosco e não como pré-requisito para se candidatar.

### Frontend Web

* O que queremos usar:

  Vuejs, Sass, PostCss, Webpack, ES6, HTML5, PWA, SSR e algumas *"cositas más"*.

* O que você precisa conhecer para se candidatar:

  HTML, CSS, Javascript.
  Ter alguma experiência com algum framework web como: AngularJS, Angular, React, Backbone OU outros.

* Níveis de experiência desejáveis:

  Estágio, Júnior, Pleno ou Sênior

## Labels

- alocação/Presencial
- experiência/Estágio
- experiência/Júnior
- experiência/Pleno
- experiência/Sênior
- regime/CLT
- regime/Estágio

**Comment by IgorHalfeld** [comment]
Eita! quanta vaga rapaz haha
Que massa!

**Comment by MoreiraVinicius** [comment]
Muito legal essa proposta de remoto e conhecimento não muito avançado. Vai ajudar muita gente

**Comment by evertonnppp** [comment]
me manda um email sobre a vaga

**Comment by H1d3l** [comment]
Existe a possibilidade de estágio remoto?

**Comment by bluuesz** [comment]
Ainda existe a vaga p/ estágio ? E aonde posso enviar meu cv ?
