### ISSUE TITLE
[Remoto] Analista Full Stack Java SR (02 vagas) @ Hagloo

### ISSUE THREAD

**Issue by giovaniPoletohagloo** [vuejs-br/vagas#360]
Responsabilidades: 

Implementar a estrutura lógica do produto, mediante construção dos serviços, que serão utilizadas pelo desenvolvedor front-end, implementação dos mecanismos de integração entre sistemas e construção de rotinas necessárias à aplicação, respeitando os cenários e regras de negócio especificadas na documentação disponibilizada. 

Conhecimentos mínimos necessários: Kotlin(desejável), Webflux, Springboot, JUnit, Docker.

Ensino Superior Completo na área de Tecnologia.
Comportamental: o projeto é bem robusto, por isso buscamos alguém sênior que tenha maturidade, proativo e que queira um desafio para atuar. É importante que tenha uma boa comunicação e trabalhe em equipe.
Localização: 100% remoto 
Data de início: 18/10

CVs: rh@hagloo.com

**Comment by giovaniPoletohagloo** [comment]
5 vagas abertas para atuar em grandes clientes.

**Comment by ErickPetru** [comment]
@giovaniPoletohagloo, este é um canal de vagas relacionadas de alguma forma a Vue e seu ecossistema. Pela descrição da stack que você publicou, não há qualquer envolvimento com Vue. Peço que reabra a vaga esclarecendo melhor caso tenha sido um engano.
