### ISSUE TITLE
[São Paulo/SP] Engenheiro Vue.js Junior/Pleno/Senior @ Stealth

### ISSUE THREAD

**Issue by raphaelsampaio** [vuejs-br/vagas#371]
## Descrição da vaga

Somos uma proptech investida por um dos maiores fundos de venture capital do Brasil e estamos em busca de engenheiros Vue.js com qualquer senioridade para compor nosso _founding team_. Nosso modelo de contratação é PJ com participação na empresa. Nossa stack é composta por Vue.js + Python + MongoDB + AWS.

## Local

São Paulo/SP - Pinheiros

## Benefícios

- Contratação PJ
- Participação na empresa

#### Diferenciais

- Startup
- Café
- Comidinhas 

## Requisitos

**Obrigatórios:**
- Alguma experiência com Vue.js (desde iniciante até expert)
- Conhecimento do protocolo HTTP
- Alguma experiência com HTML, CSS (desde iniciante até expert)

**Desejáveis:**
- Conhecimentos em algoritmos, estruturas de dados e alguma linguagem backend
- Conhecimentos em banco de dados NoSQL

**Diferenciais:**
- Projetos open-source
- Participação em comunidades

## Contratação

PJ a combinar.

## Nossa empresa

**Aqui usamos:**
- Vue.js
- HTML
- CSS
- Python
- MongoDB

## Como se candidatar

Envie uma mensagem por Whatsapp p/ 11992060606, um email para raphaelsampaio@gmail.com ou mensagem no [LinkedIn](https://www.linkedin.com/in/raphaelsampaio/)

#### Alocação
- Presencial
- Remoto

#### Experiência
- Estágio
- Júnior
- Pleno
- Sênior

#### Regime
- Estágio
- PJ

**Comment by franciscocesar** [comment]
A Vaga é totalmente Presencial ?

**Comment by raphaelsampaio** [comment]
Oi Francisco.

Podemos negociar home office 2x na semana.

Raphael Sampaio
+5511992060606

**Comment by raphaelsampaio** [comment]
> A Vaga é totalmente Presencial ?

@franciscocesar, estamos admitindo candidatos 100% remoto

**Comment by raphaelsampaio** [comment]
> Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

Vaga ainda aberta
