### ISSUE TITLE
[Portugal] FRONT-END SOFTWARE ENGINEER @ Hagloo

### ISSUE THREAD

**Issue by giovaniPoletohagloo** [vuejs-br/vagas#391]
We are looking for a Front-End Engineer, to work remotely in a very friendly and energetic environment and be part of an amazing team. If you love to learn, share knowledge, and care about creating real impact on every feature you deliver, using the latest tech stacks and having fun doing it, this is an opportunity you can't miss.

What you’ll do

Create, build, improve and optimize our web applications, by implementing new practices in continuous integration and delivery.
Build customer-faced features that will increase sales revenue and create great experiences for our travellers.
Ensure quality of our products and work closely with our product team to establish scalable solutions.
Work in a team that supports your individual growth by providing you with challenging tasks and the freedom to take new opportunities.
Who you are

3+ years of product development work.
Solid understanding of web application architecture and all of its layers.
Experienced working frameworks such as Node.js, Typescript, Javascript, Vue.js, Components, and other similar frameworks.
Enjoy building products and coding.
Knowledgeable about REST API architecture.
Report directly to our Head of Engineering and commit to constant learning and improvement.
Fluent in English.
Experienced in working with Scrum or Kanban methodologies is a plus;
Knowledge on speed improvements, Google Web Core Vitals, SEO and analytics tools is a plus.

Inglês: avançado.

CVs via: rh@hagloo.com

**Comment by viniciusdeliz** [comment]
Salary range?
