### ISSUE TITLE
[Recife/PE] Vue.js Developer @ Bleu Empreendimentos

### ISSUE THREAD

**Issue by luizpaulogodoy** [vuejs-br/vagas#45]
## Descrição da vaga

É desenvolvedor Front-end e está procurando um job?

Estamos buscando um desenvolvedor (a) front-end, de todos os níveis, para somar à nossa equipe e que goste de trabalhar em um ambiente dinâmico, aprendendo novas tecnologias.

Se você gosta de trabalhar com inovação, é antenado, auto-didata, pro-ativo, possui um bom relacionamento interpessoal e gosta ou tem interesse de trabalhar em uma empresa com foco em **Blockchain** entre em contato conosco.

## Local

Presencial, Recife - Pina(Rio Mar Trade Center)

## Benefícios

- Vale Refeição
- Plano de Saúde
- Estacionamento
- Vale Transporte
- Auxílio Combustível
- Custeio de curso/workshop/palestras de aperfeiçoamento

#### Diferenciais

- Geladeira aberta
- Café à vontade
- Chocolate e lanches livres

## Requisitos

**Obrigatórios:**
- Experiência com Vue.js
- GIT
- HTML
- CSS
- Webpack
- Javascript avançado

## Contratação

CLT

## Nossa empresa

A Bleu Empreendimentos é uma empresa voltada para criação e desenvolvimento de tecnologia em Blockchain. Combinamos a inovação e descontração para o desenvolvimento de projetos.

## Como se candidatar

Por favor envie um email para rh@bleu.com.br - enviar no assunto: [Frontend]

## Labels

- alocação/Presencial
- experiência/Pleno
- experiência/Sênior
- experiência/Júnior
- regime/CLT

**Comment by evertonnppp** [comment]
eu sou do rio de janeiro teria alguma possibilidade de ser remoto

**Comment by luizpaulogodoy** [comment]
> eu sou do rio de janeiro teria alguma possibilidade de ser remoto

Infelizmente no momento não, somente presencial.

**Comment by caiofsr** [comment]
Poderia informar a quantidade de vagas?

**Comment by luizpaulogodoy** [comment]
> Poderia informar a quantidade de vagas?

São 3 vagas.

**Comment by ErickPetru** [comment]
Olá @luizpaulogodoy. Já se passaram mais de 2 meses desde que a vaga foi aberta aqui, então... Ainda está aberta ou podemos fechar a _issue_?

**Comment by luizpaulogodoy** [comment]
> Olá @luizpaulogodoy. Já se passaram mais de 2 meses desde que a vaga foi aberta aqui, então... Ainda está aberta ou podemos fechar a _issue_?

Ainda temos uma vaga.

**Comment by ErickPetru** [comment]
Esta oportunidade se encontra aberta sem atualizações há vários meses, então estamos fechando a _issue_. Fique à vontade para abrir uma nova se houver necessidade.
