### ISSUE TITLE
[Itaperuna/RJ | Remoto] Front-end Vue.js Developer @inovany

### ISSUE THREAD

**Issue by carlosmoliv** [vuejs-br/vagas#457]
## Descrição da vaga

Desenvolver features para uma plataforma de gerenciamento de projetos, utilizando Vue.js.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com Vue.js
- Noções de UX/UI

## Contratação

PJ a combinar.

## Nossa empresa

Somos a iNova, tranformamos marcas e pessoas em expressões digitais através de uma metodologia própria e validada em centenas de projetos. https://inovany.com.br/

## Como se candidatar

Por favor envie um email para carlosoliveira@inovany.com.br com seu CV anexado - enviar no assunto: Vaga Vue.js

#### Alocação
- Remoto

#### Experiência
- Pleno

#### Regime
- PJ

**Comment by leandroslopes** [comment]
Bom dia amigo. Enviei meu currículo para você, aguardando sua apreciação. Sucesso!!!
