### ISSUE TITLE
[São Paulo/SP] Front-End Developer @ INTI

### ISSUE THREAD

**Issue by Andre-conectando** [vuejs-br/vagas#47]
Boa noite. Segue posicão para trabalhar em uma star up em forte crescimento: 

FrontEnd Developer - VUE.Js - Pleno/Senior
Requisitos
HTML;
CSS;
JavaScript - Módulos Vue.js (Vuex, Vue-Router, Vue-i18n);
Webpack 3/4;
Integrações de APIs Restful;
Experiência com libs/frameworks de teste (Jest, Cypress);
Prototipação;
Adobe Suite;
Experiência de 3+ anos em Vue.js, React.js 

Desejável: 
Experiência prévia em projetos de eCommerce;
Experiência com backend;
Conhecimentos de DEVOPS;
Conhecimento em React.js 
Conhecimento em Angular.js

Beneficios:
Plano de saúde e odontológico
Academia de Ginástica 
Ambiente informal, descontraído e acelerado

Por favor envie um email para andre.teles@conectandoprofissionais.com com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Vue.js

- regime/PJ

**Comment by IgorHalfeld** [comment]
@Andre-conectando consegue detalhar mais pra qual empresa é?

**Comment by Andre-conectando** [comment]
Igor, boa tarde!

Segue infos:

Sobre a INTI: 
Somos uma Startup em alto crescimento com gestão horizontal e ambiente cooperativo. Não só valorizamos sua opinião como esperamos que você construa a empresa com a gente!
Local - Escritório no InovaBra, São Paulo (saída da estação Paulista)
W: www.byinti.com

André Teles
Conectando Profissionais
(11) 94231 0044 (Celular)
Rua Luis Dias, 135, Itaim Bibi, SP.
www.conectandoprofissionais.com
 
 
 



De: "Igor Luiz Halfeld" <notifications@github.com>
Enviada: 2019/07/25 11:12:40
Para: vagas@noreply.github.com
Cc:  andre.teles@conectandoprofissionais.com, mention@noreply.github.com
Assunto:  Re: [vuejs-br/vagas] FrontEnd Developer (#47)
 

@Andre-conectando consegue detalhar mais pra qual empresa é?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/vuejs-br/vagas/issues/47?email_source=notifications\u0026email_token=AMWQGUVBCIQHA563IFUADN3QBGYFNA5CNFSM4IGV3NBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2ZTCJI#issuecomment-515060005", "url": "https://github.com/vuejs-br/vagas/issues/47?email_source=notifications\u0026email_token=AMWQGUVBCIQHA563IFUADN3QBGYFNA5CNFSM4IGV3NBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2ZTCJI#issuecomment-515060005", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com&qu
 ot; } } ]

**Comment by IgorHalfeld** [comment]
Não seria essa aqui: #31 ou essa aí já é outra vaga?

**Comment by ErickPetru** [comment]
Olá @Andre-conectando. Já se passaram mais de 2 meses desde que a vaga foi aberta aqui, então... Ainda está aberta ou podemos fechar a _issue_?
