### ISSUE TITLE
[Salvador/BA] Full-Stack Developer @ SimplesVet

### ISSUE THREAD

**Issue by fredmelo1** [vuejs-br/vagas#50]
## Descrição da vaga
Estamos em busca de pessoas que acreditem na máxima “missão dada, é missão cumprida” e no valor de dar e receber feedbacks sinceros. Pessoas que usem métricas e processos para ganhar cadência nas entregas. É preciso ter atenção aos detalhes, prezar pela qualidade nos códigos e ser apaixonada por codificar. Ser Desenvolvedor(a) Full Stack é ter domínio técnico e visão ampla para resolver problemas, acreditar que errar é uma oportunidade para evoluir e gostar de ser produtivo(a) e eficiente, sem fazer horas-extras. Estamos atrás de quem tenha o manifesto ágil “na veia” e seja incansável na busca por evolução.

## Local
Pituba, Salvador/Ba

## Benefícios
- Vale Alimentação
- Vale Refeição
- Vale Transporte
- Assistência Médica

#### Diferenciais
- Assistência Odontológica
- Seguro de Vida
- Vale Cultura

## Requisitos
**Obrigatórios:**
- Vue.Js
- PHP
- Rest
- MySQL
- Docker
- BDD
- Git Workflow
- Kanban

**Diferenciais:**
- Angular
- Node.js
- ElasticSearch
- Práticas de DevOps

## Contratação
CLT - 44h semanais

## Nossa empresa
Para ajudar a simplificar a gestão de clínicas veterinárias e petshops, surge a SimplesVet. Nascida em Salvador (BA), em 2013, com capital próprio, a empresa tem como produto principal um software de gestão empresarial online voltado para Clínicas Veterinárias e Petshops, também chamado SimplesVet. Nos últimos 3 anos, cresceu mais  de 70% ao ano e já é uma das ferramentas mais utilizadas pelo mercado pet nacional.

## Como se candidatar

Inscrições no link >>> http://bit.ly/2SOO7Op

## Labels

- alocação/Presencial
- experiência/Júnior
- experiência/Pleno
- regime/CLT

**Comment by ErickPetru** [comment]
Olá @fredmelo1. Já se passaram mais de 2 meses desde que a vaga foi aberta aqui, então... Ainda está aberta ou podemos fechar a _issue_?

**Comment by fredmelo1** [comment]
Valeu pela lembrança, @ErickPetru ick

> Olá @fredmelo1. Já se passaram mais de 2 meses desde que a vaga foi aberta aqui, então... Ainda está aberta ou podemos fechar a _issue_?

Valeu pela lembrança, Erick!
