### ISSUE TITLE
[Londrina/PR] Vue.js Front-End Developer @ CSG International

### ISSUE THREAD

**Issue by RafaelGorski** [vuejs-br/vagas#52]
## Descrição da vaga

CSG está formando um novo time para desenvolvimento Frontend com Vue.JS, React and Angular.  O time e o clientes falam inglês, a vaga precisa que conversação diária em inglês!

Mais detalhes da vaga em:
https://careers.csgi.com/job/CSINUS16075/Sr-Software-Development-Engineer-Frontend

## Local

Londrina

## Benefícios

- Plano de saúde Sul America Nacional
- Seguro de vida
- VR de R$ 370/mês
- Auxílio creche
- Auxilio Farmacia

#### Diferenciais

- Frutas, Café da manhã, Brunch mensal :P
- Livros que precisar
- Treinamento que precisar
- Curso de Linguas ( Inglês e Espanhol )

## Requisitos

**Obrigatórios:**
- Inglês para conversação ( intermediario para avançado, precisa sustentar convensação diaria)
- 3 anos de experiência com desenvolvimento Javascript
- 2 anos de experiência com desenvolvimento Vue.js/Angular/React
- 3 anos de experiência com desenvolvimento HTML and CSS

**Desejáveis:**
- conhecimentos em SQL
- conhecimentos em Automação de Testes Unitários
- conhecimentos em Apache Cordova
- conhecimentos em Butter CMS
- conhecimentos em Wordpress
- conhecimentos em PHP

**Diferenciais:**
- conhecimentos em .Net

## Contratação

CLT a combinar

## Nossa empresa

Empresa Americana Multinacional com escritorios no mundo todo e está expandindo a presença em Londrina com uma nova equipe de Frontend!

https://careers.csgi.com

## Como se candidatar

Por favor aplique na seguinte vaga com CV em Inglês: 
https://careers.csgi.com/job/CSINUS16075/Sr-Software-Development-Engineer-Frontend 

## Labels

- experiência/Pleno
- experiência/Sênior
- regime/CLT

**Comment by ErickPetru** [comment]
Olá @RafaelGorski. Já se passaram mais de 2 meses desde que a vaga foi aberta aqui, então... Ainda está aberta ou podemos fechar a _issue_?
