### ISSUE TITLE
[Joinville / Remoto] Pessoa Desenvolvedora Frontend Sênior na Zitrus Healthtech

### ISSUE THREAD

**Issue by armondlais** [vuejs-br/vagas#525]
**Prazer, nós somos a Zitrus Healhtech** 🤝🏽 

Você está preparado para fazer parte de uma empresa que quer transformar a gestão de saúde no Brasil, que oferece um completo pacote de benefícios, plano de desenvolvimento e está há 20 anos no mercado?  
Fazemos parte do Grupo Unimed Santa Catarina e nosso propósito é tornar-se a maior Plataforma de Soluções Tecnológicas para o Sistema Unimed em todo o Brasil 🚀  
Aqui, temos um ambiente de trabalho saudável com o olhar voltado para as pessoas, mas para esse time ficar completo só falta você!  

**O que esperamos de você para essa vaga:**

● Participar do desenvolvimento de novos projetos no time de inovação;
● Gerar código limpo e fácil de se manter, priorizando sempre a segurança e estabilidade;
● Interpretar, avaliar e criticar as soluções especificadas, indicando possíveis não conformidades;
● Compartilhar experiências e conhecimento com o time, orientando e colaborando para construir os melhores cenário;
● Efetuar testes de verificação das funcionalidades implementadas;
● Realizar o code review das atividades, mantendo a qualidade do código;
● Analisar e documentar tecnicamente as entregas.

**Requisitos técnicos necessários:**

● Experiência em HTML5/CSS3 (Design responsivo, Flexbox e Grid layout);
● Javascript / ES6+;
● Framework Vue.js ou React.js;
● SPA e controle de rotas;
● Arquitetura Flux (Vuex ou Redux);
● Integração com Restful API e Graphql;
● Experiência com controle de versões (Git) e Gitflow;
● Ativo nos processos de avaliação de pull request (code review);
● Preocupação com boas práticas e clean code;
● Experiência em framework CSS (Bulma, Bootstrap) e CSS Preprocessors (SASS, LESS);

**Contará a seu favor:**
● Habilidade com testes unitários (Vue Test Utils, Jest ou Testing Library).
● Metodologias de organização de CSS/HTML (BEM, Atomic, outros);
● Experiência com metodologias ágeis de desenvolvimento (Scrum e/ou Kanban).

**Os benefícios de trabalhar na Zitrus são:** 
● Plano de Saúde para você e dependentes (sem mensalidade 👀); 
● Plano Odontológico para você e dependentes (sem mensalidade 👀); 
● Vale Alimentação/Refeição; 
● PPR 
● Seguro de Vida; 
● Serviço de Remoção por Ambulância Unimed (SOS); 
● Convênio com Clínica Psicológica para você e seus dependentes; 
● Convênio com as farmácias para desconto em folha; 
● Prêmio Zero Falta; 
● Day off no mês do aniversário; 
● Vale transporte; 
● Auxílio Estacionamento; 
● Auxílio Creche ou babá até 6 anos de idade; 
● Flexibilidade de trabalho híbrido ou remoto. 
●  Bolsa de estudos 
● Auxílio Home Office 

**E mais:** 
● Ambiente leve e descontraído; 
● Cultura de colaboração, valorizamos que você venha para o palco e pense fora da caixa 🚀 
● Empresa em grande desenvolvimento.  

**Contratação**
PJ a combinar
CLT a combinar

**Contratação híbrida flexível para quem for de Joinville ou remota para outras cidades**.

**-> Como se candidatar <-**
Por favor envie um email para: lais.armond@zitrus.com.br com seu CV atualizado anexado e pretensão salarial - enviar no assunto: Front-End Developer Sênior.

**Aqui na Zitrus, prezamos pela Diversidade, Equidade e Inclusão. Todas as nossas oportunidades são destinadas a pessoas com deficiência, LGBTQIAP+, pessoas pretas, de diversas culturas e idades. Quanto mais diversidade, melhor** 💚

**Comment by lucasferreiralimax** [comment]
@armondlais currículo enviado
