### ISSUE TITLE
[São Paulo / Remoto / Freela] Pessoa desenvolvedora VueJS Sênior - Power Data Hub

### ISSUE THREAD

**Issue by edbizarro** [vuejs-br/vagas#53]
## Descrição da vaga

Estamos a procura de pessoa desenvolvedora comprometida e responsável para finalizar projeto já iniciado de um SPA feito em Vue.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Comprovada experiência em desenvolvimento com VueJS através de portfólio e/ou código fonte de projetos desenvolvidos
- Conhecimento em Vuex, VueRouter
- Integraçao com API rest
- Webpack
- Git

**Desejáveis:**
- Já ter integrado o plugin https://handsontable.com em algum projeto.
- Scrum
- Adobe XD

## Contratação

PJ a combinar

## Nossa empresa

Somos uma Martech com o objetivo de mudar a forma como agências e clientes trabalham com mídia e BI.

## Como se candidatar

Por favor envie um email para eduardo@powerdatahub.com com seu perfil do github e/ou Linkedin - enviar no assunto: Vaga Vue.js

## Labels

- alocação/Remoto
- experiência/Sênior
- regime/Freela
- regime/PJ

**Comment by assuncaojr** [comment]
O e-mail para contato é .com, .com.br...?

**Comment by edbizarro** [comment]
@assuncaojr obrigado pela observação, é .com, editei o texto original
