### ISSUE TITLE
[Remoto] Vue.js Developer Junior @ Port Louis

### ISSUE THREAD

**Issue by eduardonoronha** [vuejs-br/vagas#537]
## Nossa empresa
A Port Louis possui soluções de RPA para tarefas de contabilidade e financeiras. O nosso stack é composto por um front de vue, e o back em node + net core, ambos rodando em AWS.

## Descrição da vaga
Procuramos um dev júnior para crescer junto com a empresa. A atuação inicial será na resolução de bugs e desenvolvimento de pequenos features.

## Local
Remoto ou São Paulo - Jardins.

## Requisitos
_Obrigatórios:_
- Conhecimento de javascript vanila
- Conhecimento de node e as bibliotecas mais comuns
- Vontade e disposição para aprender e se desenvolver

_Desejáveis:_
- Conhecimento de banco de dados mysql
- Conhecimento de ferramentas aws - lambda, s3, ...

## Benefícios
Salário compatível com a posição
VR

## Contratação
CLT

## Como se candidatar
Por favor envie um email para eduardo@portlouis.inf.br com seu CV anexado - enviar no assunto: Vaga Vuejs

## Labels
Alocação
Presencial
Remoto
Experiência
Júnior
Regime
CLT

**Comment by isbeli** [comment]
Enviado

**Comment by tanukesensei** [comment]
Enviado.

**Comment by pumba-dev** [comment]
Done!

**Comment by hignicao** [comment]
Enviado!

**Comment by LuisSempre** [comment]
Enviado!

**Comment by LuisSempre** [comment]
Enviado!

**Comment by marcosHenrique-developer** [comment]
Enviado.

**Comment by OliverioJunior** [comment]
enviado
