### ISSUE TITLE
[Remoto] Vue Freelancer  @ MPI INFORMATICA

### ISSUE THREAD

**Issue by bernardosaltiel** [vuejs-br/vagas#538]
## Descrição da vaga
O objetivo da vaga é desenvolvedor do zero um sistema de gestão online onde iremos realizar um MVP que sera um emissor de documentos fiscais, então primeiramente iremos desenvolver toda a aparencia do projeto seguindo mockups desenhados pela equipe

## Local

Remoto 

## Requisitos

**Desejáveis:**
- Experiência com desenvolvimento JavaScript
- Experiência com desenvolvimento Vue.js

## Contratação

A combinar

## Nossa empresa

MPI Automação começamos trabalhando com automação comercial quando houve a necessidade de automatizar a nossa loja de informática e a partir disso vimos a possibilidade de um novo negocio, Então procuramos uma solução para solucionar o nosso problema na nossa loja física e depois começamos a representar essa empresa e revender o sistema deles para nossos clientes. Hoje depois de 4 anos trabalhando com automação decidimos iniciar o nosso desenvolvimento próprio de um sistema

**Aqui usamos:**
- Vue.js
- C#
- AWS

## Como se candidatar

Por favor, envie um e-mail para bernardo@mpiinformatica.com com seu CV anexado e alguns projetos feitos em vue de preferencia . Enviar no assunto: [Remoto] Vue Freelancer  @ MPI INFORMATICA

#### Alocação
- Remoto

#### Experiência
- Júnior
- Pleno
- Sênior

#### Regime
- Freela

**Comment by DayanMonteiro** [comment]
Enviado

**Comment by AndreNascimento1998** [comment]
Enviado

**Comment by isbeli** [comment]
Enviado

**Comment by pumba-dev** [comment]
Done!

**Comment by marcosHenrique-developer** [comment]
> [Remoto] Vue Freelancer @ MPI INFORMATICA

Pronto
