### ISSUE TITLE
[Porto Alegre/RS] Desenvolvedor Front-End Sênior

### ISSUE THREAD

**Issue by jokapoa** [vuejs-br/vagas#54]
## Vaga
Desenvolvedor front-end sênior

## Requisitos

**Obrigatórios:**
- +de 3 anos de experiência com  desenvolvimento usando Javascript/Typescript  com frameworks como  Angular, React ou Vue.  
- Preferencialmente,  experiência com  Angular 2+_
- 2 anos de experiência com bancos de dados relacionais e não relacionais;
- Vivencia  sólida com   Javascript, Typescript, html5,css, e ajax;
- Vivência com metodologias ágeis é importante
- Vivenca  com desenvolvimento de aplicações baseadas em plataforma cloud (AWS)
-  Inglês fluente (conversação)

## Contratação

PJ ou CLT ( a combinar).  Buscamos um profissional realmente sênior pra fazer parte do time.  A remuneração não será um obstáculo.
Obs.: A empresa oferece apoio para realocação caso o profissional venha de outra cidade/estado

## Cliente

Empresa de tecnologia, com sedes nos EUA e Europa  iniciando sua estrutura no Brasil.

## Como se candidatar

Envie seu curriculo/linkedin para frontend@holdenrh.com.br

## Labels

- CLT
- PJ
- Sênior

**Comment by ErickPetru** [comment]
Esta oportunidade se encontra aberta sem atualizações há vários meses, então estamos fechando a _issue_. Fique à vontade para abrir uma nova se houver necessidade.
