### ISSUE TITLE
[Remoto] Front-end Vue.js Developer @Kotas

### ISSUE THREAD

**Issue by jairoblatt** [vuejs-br/vagas#543]
Tem interesse em desenvolver um software que não seja o padrão empresarial comum? Sendo necessária alta performance, alta disponibilidade e atendendo a milhares de usuários todos os dias?

Então venha conhecer o Kotas 

Somos uma startup de BH que está em grande expansão e gostaríamos de te conhecer, em que você poderá contribuir?

Buscamos por pessoas que:

- Goste de novos desafios, estão dispostas a descobrir e aprender todos os dias;
- Vibram energia empreendedora: são movidas pela curiosidade, nunca desistem e estão focadas em superar seus próprios limites.
- Sejam comunicativos, colaborativos, com habilidade de organização e liderança;
- Contribuam para o design e a criação de produtos que impactam diretamente na vida de milhares de pessoas todos os dias.
- Colaborem nas definições de arquitetura, sempre pensando em soluções escaláveis.
- Programe um código de qualidade e certifique-se de que tudo funcione corretamente antes de ser implementado.

Os requisitos para o desafio são:

- Sólido conhecimento em HTML,CSS,JavaScript e Typescript;
- Sólido conhecimento em Git;
- Experiência com o framework Vue2 e Vue3;
- Experiência com ambiente ágil de integração contínua;
- Vivência com utilização de APIs REST
- Testes E2E (Cypress)
- Scss, Postcss e Tailwind
- PWA (Service workers: Push Notification, Cache, etc)

A vaga é 100% remota e PJ.

Envie o currículo para:
jairoblattc@gmail.com

**Comment by juliocaesaar** [comment]
enviei!

**Comment by leonardonicola** [comment]
enviado!

**Comment by Miguel-Domingos** [comment]
currículo enviado!

**Comment by jairoblatt** [comment]
Vaga ainda em aberto

**Comment by LuisSempre** [comment]
Enviado curriculo para a vaga!

**Comment by Miguel-Domingos** [comment]
Reenviei o curriculo para a vaga
