### ISSUE TITLE
[Manaus/AM | Remoto] Full Stack Java Vue.js Developer @ DN Consultoria

### ISSUE THREAD

**Issue by dhnasci** [vuejs-br/vagas#545]
## Desenvolvedor Full Stack Java Vue.js Pleno CLT Home Office

Somos uma startup começando a decolar. Temos projetos legais de integração com ERPs e aplicativos para empresas de logística e alimentação. 

## Manaus / AM

A vaga é remota, em regime de teletrabalho.

## Benefícios

No momento não temos mas com o crescimento da empresa vamos dar benefícios. 

#### Diferenciais

- Monte a sua máquina como desejar
- Horário flexível
- Bom Clima organizacional 

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com desenvolvimento Typescript
- 2 anos de experiência com desenvolvimento Vue.js
- 1 ano de experiência com desenvolvimento Nuxt.js
- 2 anos de experiência em Java
- 1 ano de experiência em Spring

**Desejáveis:**
- Conhecimentos em Vuex
- Banco de dados Sql Server
- BPMN
- Wordpress

**Diferenciais:**
- Projetos open-source
- Conhecimento em web-services
- Conhecimento em workflows

## Contratação

CLT

## Nossa empresa

Aqui na DN Consultoria somos líderes em aplicações web na nuvem e integrações com ERPs

**Aqui usamos:**
- Vue.js
- Java
- C#
- Heroku
- Hostinger
- Wordpress
- Intellij
- VSCode
- YouTrack
- Github
- Fusion
- Camunda

## Como se candidatar

Por favor, envie um e-mail para contato@dnconsultoria.manaus.br com seu CV anexado. Enviar no assunto: _Vaga Dev Full Stack Vue.js_

#### Alocação
- Remoto

#### Experiência
- Pleno

#### Regime
- CLT

**Comment by Shnrqpdr** [comment]
Enviado!

**Comment by juliocaesaar** [comment]
Enviado!

**Comment by dhnasci** [comment]
## Status
Estou fechando a Issue, contudo a vaga ainda **está em aberto.** 
As pessoas que se candidataram estão no processo de seleção. 
Em breve daremos retorno.
Agradecemos a todos os organizadores deste canal.  😄
