### ISSUE TITLE
[Espírito Santos | Vitória/ES | Presencial] Front-end Developer @ {Code n'App}

### ISSUE THREAD

**Issue by Inglidbarbosa** [vuejs-br/vagas#547]
## Descrição da vaga

RESPONSABILIDADES E ATRIBUIÇÕES
A pessoa desenvolvedora plena será responsável pela criação e evolução do front-end de sistemas web, utilizando de frameworks JS, HTML e CSS, assim como técnicas de responsividade, fidelidade ao protótipo, apoio à equipe de devs, mapeamento de tarefas e atividades das implementações a serem executadas pela equipe e por si próprio. Tendo a oportunidade de atuar internamente ou em parceiros, confiante em todo o ciclo de vida, desde a concepção até a implantação, esteve com metodologias ágeis para entregar uma solução eficiente. 

Etapas do processo seletivo:
Inscrição e avaliação inicial (Dica: mantenha seu currículo atualizado na plataforma);
Triagem (Para essa etapa, vão as pessoas com mais aderência à descrição da vaga)
Entrevista comportamental e técnica (Com o tempo de pessoas e cultura e o Gestor da área);
Feedback e/ou formalização da proposta.

## Local

Presencial em Vitória ES

## Benefícios

Nosso ambiente foi preparado para que você que goste de compartilhar experiências, ama resultados e adora se divertir com os desafios do dia a dia. E mais, pense em como melhorar tudo isso com um pacote de benefícios:
⏰Possibilidade de resistência e de modelo híbrido;
👕Sem código de vestimenta;
🏋🏽‍♀️ Gympass;
🧘‍♂️Apoio a saúde mental (Em parceria com a plataforma Psymeet);
🩺Assistência médica (você + parceiro(a) + filhos até 18 anos é por nossa conta);
🦷Assistência odontológica;
🥗Alimentação: Pra que escolher entre alimentação ou refeição se você pode ter os dois em um só? Além de um saldo livre para utilização nas categorias de mobilidade, cultura, saúde e home office;
🚍Vale transporte;
🎉Celebração de datas importantes (Seu aniversário, aniversário Code n' App, etc.);
🛏️Day off (folga no aniversário);
📚Acesso gratuito à plataforma Udemy;
💸Um clube de vantagens incríveis onde você pode desfrutar de vários descontos em diversas categorias como alimentação, turismo, instituições de ensino e
etc.

🤑Programa Indica Code - (Indicando um amigo você ganha um bônus de R$ 500,00 por talento contratado);
🤱🏽 Cesta recém-nascido;
🍪Cafézinho e biscoitos à vontade, além de puffs para cochilar nos intervalos;
💰Assessoria e educação financeira;
💵Empréstimo consignado;
👨🏽‍💻 Oportunidade de fazer parte de um tempo de feras e com muitas experiências para compartilhar.
🦽Todas as nossas vagas estão disponíveis para pessoas com deficiência!

## Requisitos

Contribuir para o sucesso do projeto e crescimento da equipe;
Conhecer as boas práticas de programação das tecnologias utilizadas;
Apoiar a equipe no desempenho de suas atividades;
Propor melhorias ao sistema projetado;
Possuir visão sistêmica do projeto, avaliando riscos do desenvolvimento e efeitos que envolvem a atuação da equipe;
Escrever código limpo, de qualidade e de fácil manutenção.
REQUISITOS E QUALIFICAÇÕES
Graduação ou Tecnólogo completo em áreas de tecnologias da informação;

Experiência no desenvolvimento de interfaces web, utilizando React JS e/ou Vue JS;

Sólidos conhecimentos em:
HTML/CSS/Javascript;
Datilografado;
Reagir JS;
API de contexto;
Git e GitFlow;
Experiência em metodologias ágeis como Scrum.

## Contratação

CLT ou PJ

## Nossa empresa

Somos uma empresa que é a-pai-xo-na-da por tecnologia, que através do desenvolvimento de software e processos, buscamos soluções inovadoras e totalmente customizadas para cada um dos nossos clientes a fim de alcançar o melhor resultado, independente da tecnologia utilizada .

Além disso, estamos em um ritmo de crescimento a-ce-le-ra-do, então se você curte desafios, busca evoluir e ama tecnologia, temos aqui um tempo para chamar de seu! Pois adoramos reconhecer e potencializar o desenvolvimento dos nossos Codenappers.

#VemPraCode♥

## Como se candidatar

https://codenapp.gupy.io/jobs/4448266

#### Alocação
- Presencial

#### Experiência
- Pleno

#### Regime

- CLT ou
- PJ

**Comment by rayanmarcus** [comment]
Apliquei para a vaga!
Por acaso aceitarão negociar atuar no modo home office (espero que sim🙏)?

**Comment by Inglidbarbosa** [comment]
Oi Ryan, bom dia!
Você é daqui do ES? (ainda não olhei seu cadastro)
Porque a princípio é full presencial, mas depois de um tempo nós conseguimos flexibilizar.

[Code n' App]   Inglid Barbosa
Analista de Pessoas e Cultura

________________________________
De: Rayan Marcus ***@***.***>
Enviado: quarta-feira, 15 de março de 2023 03:29
Para: vuejs-br/vagas ***@***.***>
Cc: Inglid Magda dos Santos Barbosa ***@***.***>; Author ***@***.***>
Assunto: Re: [vuejs-br/vagas] [Espírito Santos | Vitória/ES | Presencial] Front-end Developer @ {Code n'App} (Issue #547)


Apliquei para a vaga. Por acaso aceitarão home office (espero que sim🙏)?

**Comment by rayanmarcus** [comment]
Oi Inglid
Eu sou do interior do Rio

**Comment by lipecss** [comment]
Olá, sou de São Paulo e gostei bastante vaga. Realmente não aceitam na modalidade home office?
