### ISSUE TITLE
[Rio de Janeiro/RJ | Remoto] Vue.js Front-End Developer @ Storyblok

### ISSUE THREAD

**Issue by onefriendaday** [vuejs-br/vagas#55]
## Descrição da vaga

Estamos procurando 2-3 desenvolvedores front-end de Estágio até Senior.

## Local

Remoto ou escritório
Linz - Austria, Barra da Tijuca ou Teresópolis - Rio de Janeiro

## Requisitos

**Obrigatórios:**
- Experiência (ou interesse de aprender) com Vue.js (Nosso front é em Vue.js) ou React
- Inglês intermediário

**Diferenciais:**
- Projetos open source
- Blog ou vontade the escrever
- Experiência com AWS

Nessa função, você estará trabalhando em novas funcionalidades, integrações com aplicativos de terceiros e código open source (como o Nuxt.js, o Next.js, o Gatsby ...) para melhorar a experiência para nossos clientes. Você também terá a oportunidade de colaborar no nosso blog para escrever artigos e tutoriais. Com a nossa sede em Linz, na Áustria, e o escritório satélite no Rio de Janeiro, Brasil, você poderá se juntar a uma equipe de trabalho remoto ou no escritório.

## Contratação

PJ ou CLT ( a combinar). A remuneração não será um obstáculo.

## Nossa empresa

A Storyblok foi fundada em 2017 com a missão de construir um CMS moderno para desenvolvedores, designers e editores. Desde então, temos visto um crescimento inacreditável na comunidade e uso em escala global, capacitando pessoas e empresas em mais de 131 países.

## Como se candidatar

Por favor envie um email para af@storyblok.com

## Labels

- alocação/Flexível
- experiência/Estágio
- experiência/Júnior
- experiência/Pleno
- regime/A-Combinar

**Comment by IgorHalfeld** [comment]
Muito massa!

**Comment by emanuelgsouza** [comment]
Vaga muito interessante!

**Comment by onefriendaday** [comment]
> Vaga muito interessante!

Vamos conversar @emanuelgsouza :)

**Comment by fafa1** [comment]
Bom dia, tenho experiência na stack citada acima; só aceitam ingês fluente?

**Comment by onefriendaday** [comment]
> Bom dia, tenho experiência na stack citada acima porém sem o requisito do inglês fluente; só aceitam ingês fluente?
> grato!

Bom dia! Aceitamos Inglês intermediário também.

**Comment by victorhsantiago** [comment]
Existe a possibilidade de visto para ir para Austria?

**Comment by victorhsantiago** [comment]
Olá, existe a possibilidade de visto para ir para Austria?

**Comment by lpj145** [comment]
Qual o fuso horario pro trabalho ? toda a comunicação dentro da empresa é ingles ?

**Comment by rodrigorhas** [comment]
Vaga muito boa. Enviei o e-mail, espero que dê certo.

**Comment by EduardoFMP** [comment]
Vaga interessantíssima! :)

**Comment by onefriendaday** [comment]
> Qual o fuso horario pro trabalho ? toda a comunicação dentro da empresa é ingles ?

Fuso horário é do Rio de Janeiro. A comunicação é Inglês sim.

**Comment by lpj145** [comment]
Com relação a carga como vocês pretenderiam ? 8h/Dia 8 as 16 ?

**Comment by onefriendaday** [comment]
> Com relação a carga como vocês pretenderiam ? 8h/Dia 8 as 16 ?

A combinar

**Comment by feduardof** [comment]
O currículo e e-mail devem ser enviados em inglês? Aceitam part-time?

**Comment by cairoramos7** [comment]
Ainda á vagas?

**Comment by onefriendaday** [comment]
> Ainda há vagas?

Sim, ainda tem

**Comment by ErickPetru** [comment]
Esta oportunidade se encontra aberta sem atualizações há vários meses, então estamos fechando a _issue_. Fique à vontade para abrir uma nova se houver necessidade.
