### ISSUE TITLE
[Campinas/SP | Local] Jr/Pl Front-end Vue.js Developer @ FanBase

### ISSUE THREAD

**Issue by anakais** [vuejs-br/vagas#553]
## Descrição da vaga
Olá, somos a maior start-up de esportes do Brasil. Trabalhamos com clubes, ligas, federações e etc. Estamos começando a pegar cada vez mais clubes grandes e precisamos de pessoas que queiram fazer parte dessa fase pioneira, ou seja, em que as coisas ainda estão se organizando, mudanças ocorrem de forma rápida, entregas são feitas às vezes no mesmo dia. Aos poucos estamos nos tornando maiores e com mais processos mas essa fase atual é única e uma ótima oportunidade para quem busca se desenvolver em um pouco de tudo de forma rápida. Muito diferente de entrar em um empresa grande, já toda estruturada, aqui muitos dos processos e descoberta da soluções devem vir de nós mesmos, de cada programador - claro que com todo o apoio e colaboração da equipe. Se você gosta de programar com Vue.js, tailwind e Nuxt, ou tem interesse em aprender, e encara o desafio de fazer parte de uma start-up no seu breve início. Vamos pra cima, mande seu currículo e entre contato conosco!

## Local
Escritório, Campinas/SP - Galleria Office Park
*Por estarmos no começo, buscamos apenas quem quer _trabalhar localmente_. A ideia é dentro de um ano já estarmos mais azeitados para uma cultura remota/híbrida.

## Benefícios
- PJ
- VR de R$ 500/mês (Caju Benefícios)

#### Diferenciais
- Horário de almoço f lexível
- Máquina da empresa para trabalhar
- Fruteira sempre cheia
- Por enquanto nosso único esporte é o Xadrez =P

## Requisitos
**Obrigatórios:**
- 2 anos de experiência com desenvolvimento JavaScript
- 1 ano de experiência com desenvolvimento Vue.js

**Desejáveis:**
- Conhecimento com desenvolvimento em Nuxt.js
- Conhecimento com desenvolvimento em Tailwind CSS

**Diferenciais:**
- Curtir esportes em geral, futebol, vôlei, tênis de mesa, UFC, surf...

## Contratação
PJ a combinar.

## Nossa empresa
Aqui na FanBase nós ajudamos Clubes, Ligas, Atletas, Artistas, Eventos e seus parceiros e patrocinadores a maximizar a relação com seus fãs. Já somos a maior startup de esportes do Brasil.

**Aqui usamos:**
- Vue.js 2 e 3
- Tailwind 
- Nuxt
- C#
- AWS
- SQL

## Como se candidatar
Por favor, envie um e-mail para alexandre@fanbase.com.br com seu CV anexado. Enviar no assunto: _Vaga Vue.js_

#### Alocação
- Presencial

#### Experiência
- Júnior
- Pleno

#### Regime
- A-Combinar
- PJ

**Comment by lucaspmarra** [comment]
Bom dia, possibilidade de Remoto?

**Comment by anakais** [comment]
> Bom dia, possibilidade de Remoto?

Infelizmente, no momento não Lucas. Um abraço!

**Comment by felipalb** [comment]
Enviei email, atendo a todos os requisitos, tenho grande interesse
