### ISSUE TITLE
[São Paulo/SP] Desenvolvedor Front-End Vue.js Sênior @ Ultréia

### ISSUE THREAD

**Issue by rodneivete** [vuejs-br/vagas#56]
## Descrição da vaga

Desenvolvimento de novos projetos com Vue.js, manutenção e migração de outras tecnologias.

## Local

Presencial, São Paulo - Chácara Santo Antônio

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento Javascript
- experiência com Vuex, vue-router, vue-i18n, axios

**Desejáveis:**
- automação de testes

**Diferenciais:**
- noções de Java

## Contratação

PJ a combinar

## Nossa empresa

Somos uma empresa com foco em sistemas para indústria farmacêutica, tendo como clientes as principais indústrias do mercado.

## Como se candidatar

Por favor envie um email para rodnei.vete@ultreia.com,br com seu CV anexado - enviar no assunto: Vaga Vue.js

## Labels

- alocação/Presencial
- experiência/Pleno
- experiência/Sênior
- regime/PJ

**Comment by ErickPetru** [comment]
Esta oportunidade se encontra aberta sem atualizações há vários meses, então estamos fechando a _issue_. Fique à vontade para abrir uma nova se houver necessidade.
