### ISSUE TITLE
[ Remoto] Front-end Vue.js Developer @ {Nt Consult}

### ISSUE THREAD

**Issue by hamiltongabriel** [vuejs-br/vagas#574]
## Descrição da vaga

A NTConsult é uma organização líder global em desenvolvimento de software personalizado e aumento da equipe de TI. Nossos centros de desenvolvimento estão localizados na América Latina, onde por quase duas décadas construímos soluções de software de ponta e aumentamos as equipes de tecnologia.

www.ntconsultcorp.com

O Que Estamos Procurando 🚀

Profissionais prontos para encarar os desafios que irão aparecer! Estando sempre dispostos a crescer e evoluir, sabendo que a empresa poderá dar os meios possíveis para tanto.

Informações Adicionais ℹ️

Buscamos profissionais De desenvolvimento Front end com experiência com Vue.js e para atuação em projetos de segmento financeiro/seguros. 💰

Atribuições da Posição

• Propor evoluções tecnológicas em sistemas financeiros;
• Monitorar a execução das boas práticas de desenvolvimento de sistemas;
• Monitorar o desempenho e performance dos sistemas das aplicações;
• Antecipar-se a oportunidades e problemas, agindo com rapidez e eficácia, desenvolvendo soluções de forma preventiva;

## Requisitos

**Obrigatórios:**
- Vue 3;
- TypeScript;
- Design System;
- Vuetify;
- Pinia / Composition API do Vue ou Vuex
- Vite e Webpack;
- Experiência com testes nas ferramentas: Jest, Vue Test Utils, Cypress;
- Storybook;
- TailwindCSS + Sass;
- web components.

**Desejáveis:**
- SEO e performance;
- Experiência com ferramentas de ci/cd; 
- csrf e xss.
## Contratação

PJ a combinar.

## Como se candidatar

Entrar em contato com Bruno Muller no linkedin
https://www.linkedin.com/in/brunom%C3%BCller/

https://www.linkedin.com/jobs/view/pessoa-desenvolvedora-front-end-vue-sr-at-ntconsult-3799077971/?originalSubdomain=br

#### Alocação
- Remoto

#### Experiência
- Pleno
- Sênior

#### Regime

- PJ

**Comment by nazarepiedady** [comment]
@hamiltongabriel, continuam a recrutar?
