### ISSUE TITLE
[Remoto] Fullstack Vue.js Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [vuejs-br/vagas#577]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/fullstack-developer-180023302?utm_source=github&utm_medium=vuejs-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Estamos com vaga aberta para <strong>Fullstack Developer</strong>, para trabalhar junto ao nosso time de Produto. O objetivo é trabalhar com metodologias de mensuração de impactos ambientais e sociais das empresas para diferentes projetos.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Definir padrões de arquitetura e apoiar o crescimento tecnológico;</li>
<li>Apoiar no crescimento do produto, desenvolvendo funcionalidades, ferramentas e serviços;</li>
<li>Desenvolver código de alta qualidade, escalável, limpo e testável, seguindo as melhores práticas de desenvolvimento de software;</li>
<li>Coordenar equipes internas no entendimento dos requisitos do usuário e fornecer soluções técnicas.</li>
</ul>
## Deep ESG: 
 <p>Medir os impactos que importam hoje, para mudar o mundo amanhã: esse é o propósito da DEEP.&nbsp;&nbsp;</p>

<p>Acreditamos que as métricas de sustentabilidade são essenciais para mensurar a extensão do que o capital investido produz na sociedade.&nbsp;</p><a href='https://coodesh.com/companies/deepesg'>Veja mais no site</a>

 ## Habilidades: 
 - Vue.js 
- Typescript 
- Nest.JS 
- API
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência sólida em desenvolvimento web; 
- Experiência com frameworks modernos de componentes em TypeScript, como React ou Vue. Preferencialmente Vue; 
- Experiência com desenvolvimento de API em TypeScript, preferencialmente em Nest.js; 
- Conhecimento de padrões de arquitetura; 
- Conhecimento avançado em bancos de dados relacionais; 
- Excelentes habilidades de resolução de problemas e capacidade de trabalhar em equipe.
## Diferenciais: 
 - Experiência com o framework Vue.js (Versão 3+); 
- Familiaridade com práticas de DevOps e ferramentas como Docker e Kubernetes; 
- Experiência em integração contínua e entrega contínua (CI/CD); 
- Conhecimento em testes automatizados e frameworks de teste, como Jest ou Vitest; 
- Habilidades de liderança técnica e capacidade de orientar e mentorar outros membros da equipe.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer na Deep ESG](https://coodesh.com/jobs/fullstack-developer-180023302?utm_source=github&utm_medium=vuejs-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by linspw** [comment]
Ola tenho interesse em me candidatar, percebi que a vaga está congelada. Caso venha a reabrir, tenho muita disposição e interesse em me tornar candidato. Tenho domínio em todos os requisitos apresentados.

**Comment by FrancieleGhizzoni** [comment]
@linspw Aviso se precisarmos de mais candidatos, pode deixar!

**Comment by linspw** [comment]
Obrigado @FrancieleGhizzoni
