### ISSUE TITLE
[Remoto] Vue.js Developer Junior @ Port Louis

### ISSUE THREAD

**Issue by andregodeiro** [vuejs-br/vagas#587]
## Nossa Empresa
A Port Louis possui soluções de RPA para tarefas de contabilidade e financeiras. O nosso stack é composto por um front de vue, e o back em node + net core, ambos rodando em AWS.

## Descrição da vaga

Na Port Louis, valorizamos a contratação de desenvolvedores juniores e estagiários, visando seu crescimento em conjunto conosco e seu contínuo desenvolvimento profissional.

Operamos com projetos ágeis, constituídos por squads de 5 a 9 membros, utilizando a metodologia Scrum. Realizamos sprints quinzenais, com rituais de planning, dailies, review e revisão de roadmap.

**Aqui usamos:**
- Vue.js
- Typescript
- C#
- AWS

## Local

Remoto ou São Paulo/SP - Jardins

## Benefícios

- Plano de saúde
- Seguro de vida
- VA

## Requisitos

**Obrigatórios:**

Conhecimento de javascript vanila
Conhecimento de node e as bibliotecas mais comuns
Vontade e disposição para aprender e se desenvolver

**Desejáveis:**
Conhecimento de banco de dados MySQL e PostgreSQL
Conhecimento de ferramentas AWS (Lambda, S3, etc.)

## Contratação

CLT

## Como se candidatar

Vaga preenchida

#### Alocação
- Remoto

#### Experiência
- Júnior

#### Regime
- CLT

**Comment by Miguel-Domingos** [comment]
@andregodeiro enviado
