### ISSUE TITLE
[São Paulo/SP] Desenvolvedor Front-End Vue.js @ DOC88

### ISSUE THREAD

**Issue by gbgelado** [vuejs-br/vagas#59]
## Descrição da vaga

Estamos procurando desenvolvedores front-end Pleno e Senior para trabalhar com Vue.js.

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios

- Plano de saúde/odonto
- VR/VA
- Vale Cultura
- Auxílio Academia na Bodytech
- Estacionamento

#### Diferenciais

- workshops semanais sobre assuntos variados (você também pode palestrar)
- frutas
- lanches da tarde, pizza e churrasco não faltam 
- geladeira da Rochinha

## Requisitos

**Obrigatórios:**
- Experiência com Vue.js e Vuex
- Experiência com Sass

**Desejáveis:**
- conhecimentos em Nuxt.js

**Diferenciais:**
- NativeScript
- experiência com Scrum
- conhecimentos em Flutter

## Contratação

CLT, remuneração á combinar

## Nossa empresa

A DOC88 é uma empresa de tecnologia que integra o grupo Comerc e tem como ideal encontrar maneiras disruptivas para melhorar a gestão e a produtividade dos nossos clientes. Estamos sempre prontos para auxiliar no desenvolvimento de projetos de forma inteligente e funcional. E como fazemos isso? Por meio de um processo estruturado baseado em análises, consultorias e desenvolvimentos de plataformas e soluções digitais específicas para cada negócio. E o melhor de tudo: todos esses processos são tocados por um bando de apaixonados por tecnologia. Investimos também em projetos de IoT e Blockchain.

## Como se candidatar

Por favor envie um email para [henry.fila@doc88.com.br](mailto:henry.fila@doc88.com.br) com seu CV anexado - enviar no assunto: Vaga Front-end

## Labels

- alocação/Presencial
- experiência/Pleno
- experiência/Sênior
- regime/A-Combinar
- regime/CLT

**Comment by ErickPetru** [comment]
Esta oportunidade se encontra aberta sem atualizações há vários meses, então estamos fechando a _issue_. Fique à vontade para abrir uma nova se houver necessidade.
