### ISSUE TITLE
[São Paulo/SP | Remoto] Front-end Vue.js Developer @ {NT Consult}

### ISSUE THREAD

**Issue by ruanfelssner** [vuejs-br/vagas#590]
A NT: Somos uma consultoria global de desenvolvimento de software personalizado e contratação de projetos de TI sem restrições geográficas; operamos globalmente, navegando em desafios tecnológicos e empresariais com expertise. Nossa sede nos Estados Unidos está localizada em San Diego, Califórnia, e também temos centros de desenvolvimento estrategicamente localizados no Brasil, México, Peru e Uruguai. Nossa sede na América Latina está sediada em Porto Alegre, Brasil, com uma filial em São Paulo. Há mais de duas décadas, somos reconhecidos globalmente no mercado de software e inovação por entregar projetos com valor agregado, elaborados por equipes ágeis de profissionais qualificados. Confira nossa página nacional e internacional em: [www.ntconsult.com.br](http://www.ntconsult.com.br/) e [www.ntconsultcorp.com](http://www.ntconsultcorp.com/).
 
 
O projeto: Estamos procurando excepcionais profissionais em desenvolvimento Front-end Vue.js para esta oportunidade totalmente remota de trabalhar em um cliente, uma seguradora que conta com recursos globais e autonomia local, atendendo às necessidades específicas, e promovendo soluções diferenciadas e inovadoras. Atua nos segmentos comercial, industrial, varejo e digital, presente em mais de 100 países nos ramos de seguros e resseguros há mais de 35 anos.
 
As responsabilidades:

-  Propor evoluções tecnológicas em sistemas financeiros;
-  Monitorar a execução das boas práticas de desenvolvimento de sistemas;
-  Monitorar o desempenho e performance dos sistemas das aplicações;
-  Antecipar-se a oportunidades e problemas, agindo com rapidez e eficácia, desenvolvendo soluções de forma preventiva.

Os requisitos mandatórios:

- Experiência com Vue/Nuxt 3.
- Experiência com TypeScript.
- Experiência com Design System.
- Experiência com Pinia / Composition API do Vue / Vuex.
- Experiência com Vite e Webpack.
- Experiência com testes nas ferramentas: Jest, Vue.js Test Utils, Cypress.
- Experiência com Storybook.
- Experiência com TailwindCSS e Sass.
- Experiência com Web Components.
- Experiência com Figma

Os diferenciais:

- Experiência com SEO e Performance.
- Experiência com ferramentas de CI/CD.
- Experiência com CSRF e XSS.

Link da vaga: https://ntconsult.compleo.com.br/Visualizar/179046
Recrutadora: https://www.linkedin.com/in/julianaduque-/

**Comment by hosanabarcelos** [comment]
Tenho forte interesse na vaga!
