### ISSUE TITLE
[São Paulo/SP] Desenvolvedor Front-End Vue.js Pleno/Sênior @ Influu

### ISSUE THREAD

**Issue by influu** [vuejs-br/vagas#62]
## Descrição da vaga
Desenvolvimento de novos projetos e manutenções com Vue.js.

## Local

Presencial, São Paulo - Metro Faria Lima

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento Javascript
- 2 anos de experiência com desenvolvimento Vue.js/Nuxt

**Desejáveis:**
- conhecimentos em Vuex

## Contratação

PJ a combinar

## Nossa empresa

Somos uma agência com foco no mercado de influenciadores

## Como se candidatar

Por favor envie um email para contato@influu.me com seu CV anexado - enviar no assunto: [Vaga Vue.js] + Nome_Sobrenome

## Labels

- alocação/Flexível
- alocação/Presencial
- experiência/Pleno
- experiência/Sênior
- regime/PJ

**Comment by ErickPetru** [comment]
Esta oportunidade se encontra aberta sem atualizações há vários meses, então estamos fechando a _issue_. Fique à vontade para abrir uma nova se houver necessidade.
