### ISSUE TITLE
[Ouro Preto/MG | Remoto] Front-End Software Engineer @ STILINGUE

### ISSUE THREAD

**Issue by Barbara-cristina** [vuejs-br/vagas#63]
## Local

Presencial em Ouro Preto-MG ou Remoto

## Requisitos

- Avançado de HTML e CSS;
- JavaScript/Jquery - Domínio da linguagem da internet;
- Version Control/Git - Experiência com ferramentas de versionamento;
- Python - Bom conhecimento de Python (Google AppEngine);
- Design Pattern(Padrões de código) - Ter conhecimento dos padrões tradicionais de JS e Python;
- Responsive Design - Entender responsividade e saber implementá-la; - bootstrap
- Testing/Profiling/Debugging - Consegue entender e prevenir erros com facilidade.

**Diferenciais:**
- Vue.js
Squads
Browser Development Tools - Otimizar códigos web;

## Contratação

PJ a combinar

## Nossa empresa

A STILINGUE é uma plataforma de Inteligência Artificial (IA) que permite a gestão de marcas em real time, com base na opinião espontânea dos consumidores nos canais digitais. Nossa tecnologia é admirada pelos mais modernos Departamentos de Marketing da América Latina, mais precisa que grandes nomes estrangeiros de Inteligência Artificial e a mais usada no Brasil, segundo pesquisa dos profissionais de redes sociais.

## Como se candidatar

Por favor envie um email para pessoas@stilingue.com.br com seu CV anexado - enviar no assunto: Vaga - Front End

## Labels

- alocação/Remoto
- alocação/Presencial
- experiência/Pleno
- experiência/Sênior
- regime/PJ

**Comment by ErickPetru** [comment]
Esta oportunidade se encontra aberta sem atualizações há vários meses, então estamos fechando a _issue_. Fique à vontade para abrir uma nova se houver necessidade.
