### ISSUE TITLE
[São Paulo/SP] Front-end Developer @ CCC

### ISSUE THREAD

**Issue by wilnerjs** [vuejs-br/vagas#76]
## Descrição da vaga

Profissional para trabalhar focado no front-end de aplicação já existente na empresa. 

## Local
Escritório em SP - Vila Olimpia

## Requisitos
- Experiência com desenvolvimento Javascript e Vue.js

## Contratação

PJ a combinar

## Nossa empresa

Empresa de consultoria financeira.

**Aqui usamos:**
- JAVA
- Javascript
- Vue.Js
- PostgreSql

## Como se candidatar

Por favor envie um email para wilnerjs@hotmail.com com seu CV anexado - enviar no assunto: Vaga Vue.js

**Comment by IgorHalfeld** [comment]
Tem mais alguma informação da empresa? site?
