### ISSUE TITLE
[São José dos Campos/SP] Desenvolvedor Front-end @ GSW Software

### ISSUE THREAD

**Issue by marianabompean** [vuejs-br/vagas#78]
###  **Descrição da vaga**
Atuar em grande projeto.
Projeto: Tempo indeterminado

### **Local**
São José dos Campos

### **Benefícios**

Á combinar

### **Requisitos**

- Domínio avançado de HTML5 e CSS3
- Javascript( React, Angular);

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento Javascript
- 1 ano de experiência com desenvolvimento React

### **Contratação**
PJ 

### **Nossa empresa**
A GSW é uma empresa referência, no desenvolvimento de soluções em Tecnologia da Informação, oferece a seus clientes sistemas de TI que se traduzem em melhorias significativas para o dia a dia do negócio, principalmente no que se refere à redução de custos e ao aumento da produtividade. Clientes: SPC Brasil, Embraer, Ericsson, Panasonic etc..

### **Como se candidatar**

Por favor, envie um email para mariana.bompean@gsw.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

### Labels

- alocação/Presencial
- experiência/Pleno
- experiência/Sênior
- regime/PJ

**Comment by heliomsolivas** [comment]
Tá certo isso?

Requisitos
Javascript( React, Angular);
